"""Lote 2 do pacote diário: mais 50 carrosséis perenes (sites e negócios, IA na prática, tecnologia e segurança)."""
from conteudo import P, POSTS, nao, atencao, cinza, copie, X, CORAL, AZUL  # noqa: F401
from modelo import stat, lista, linha, fluxo, aviso, pilula, barras, browser, texto  # noqa: F401

INICIO_LOTE2 = len(POSTS)

# =============================================================== SITES E NEGÓCIOS (20)

P("5-paginas-que-todo-site-precisa", "site",
  "As 5 páginas que todo site de empresa precisa ter.",
  "Início, Sobre, Serviços, Contato e Política de Privacidade. Cada uma com uma função clara.",
  "#criacaodesites #sitesprofissionais #webdesign #empreendedorismo #negocios",
  "Seu site tem as 5?",
  [("<p>As <b>5 páginas</b> que todo site de empresa precisa ter.</p><p>Cada uma com uma função clara.</p>",
    [stat("5", "Páginas", "essenciais", size=200),
     lista("Mapa do site", ["Início", "Sobre", "Serviços", "Contato", "Privacidade"], icon="→", fs=26)]),
   ("<p><b>Início:</b> diz em segundos o que você faz, para quem, e leva ao contato.</p>",
    [lista("Início", ["Promessa clara", "Botão de ação", "Resumo dos serviços"])]),
   ("<p><b>Sobre:</b> mostra quem está por trás e por que confiar.</p><p><b>Serviços:</b> explica o que você entrega, sem enrolação.</p>",
    [lista("Sobre", ["História curta", "Fotos reais"]), lista("Serviços", ["O que entrega", "Para quem"], black=True)]),
   ("<p><b>Contato:</b> WhatsApp, formulário, endereço e horário, tudo em um lugar.</p>",
    [lista("Contato", ["WhatsApp", "Formulário", "Endereço e mapa", "Horário"])]),
   ("<p><b>Política de privacidade:</b> obrigatória quando o site coleta dados, pela LGPD.</p>",
    [texto("Privacidade", 'Coletou dados? <span class=coral>Explique como usa.</span>', black=True, fs=42)]),
   ])

P("o-que-e-hospedagem-de-site", "site",
  "Domínio é o endereço. Hospedagem é o terreno. Entenda a diferença.",
  "O domínio é o nome que o cliente digita. A hospedagem é o servidor onde os arquivos do site ficam guardados e funcionando 24 horas.",
  "#hospedagem #dominio #criacaodesites #tecnologia #negocios",
  "Endereço e terreno, os dois no seu nome.",
  [("<p><b>Domínio</b> é o endereço. <b>Hospedagem</b> é o terreno.</p><p>Entenda a diferença.</p>",
    [texto("Domínio", 'O <span class=blue>endereço</span>: suaempresa.com.br', black=True, fs=34),
     texto("Hospedagem", 'O <span class=coral>terreno</span>: onde o site fica', fs=34)]),
   ("<p>A hospedagem é um <b>servidor</b>, um computador ligado 24 horas, onde os arquivos do seu site ficam guardados.</p>",
    [aviso("Servidor", "ligado 24 horas por dia", "🖥", black=False, cor=AZUL)]),
   ("<p>Quando alguém digita o seu domínio, a internet descobre em qual servidor o site está e mostra a página.</p>",
    [fluxo("O caminho", ["Cliente digita o domínio", "A internet acha o servidor", "O site aparece"])]),
   ("<p>O que observar numa hospedagem: <b>estabilidade</b>, velocidade, cópia de segurança e suporte.</p>",
    [lista("Boa hospedagem", ["Estabilidade", "Velocidade", "Backup", "Suporte"])]),
   ("<p>E a regra de sempre: domínio e hospedagem <b>no seu nome</b>, com o seu acesso.</p>",
    [texto("Regra", 'Tudo <span class=coral>no seu nome</span>, com a sua senha.', black=True, fs=42)]),
   ])

P("cadeado-https-no-site", "site",
  "Aquele cadeado na barra do navegador importa mais do que parece.",
  "O HTTPS protege os dados entre o visitante e o site. Sem ele, o navegador pode mostrar o aviso de site não seguro.",
  "#https #seguranca #criacaodesites #tecnologia #negocios",
  "Confira agora se o seu site tem o cadeado.",
  [("<p>Aquele <b>cadeado</b> na barra do navegador importa mais do que parece.</p>",
    [pilula("Barra do navegador", "🔒 https://suaempresa.com.br", "Conexão protegida")]),
   ("<p>O cadeado indica <b>HTTPS</b>: os dados trocados entre o visitante e o site viajam criptografados.</p>",
    [texto("HTTPS", 'Dados <span class=coral>criptografados</span> no caminho.', fs=42)]),
   ("<p>Sem HTTPS, navegadores podem exibir o aviso de <b>\"não seguro\"</b>, principalmente em páginas com formulário.</p>",
    [aviso("Não seguro", "o que o visitante vê sem HTTPS", "!", cor=CORAL)]),
   ("<p>Para ativar, o site precisa de um <b>certificado SSL</b>. Muitas hospedagens já oferecem gratuitamente.</p>",
    [lista("Como ter", ["Certificado SSL", "Oferecido pela hospedagem", "Renovação automática"])]),
   ("<p>Depois de ativar, confira se <b>todas as páginas</b> abrem com https, inclusive o formulário.</p>",
    [lista("Checagem", ["Página inicial", "Formulário", "Todas as páginas"])]),
   ])

P("site-de-uma-pagina-ou-varias", "site",
  "Site de uma página só ou com várias páginas? Depende do seu negócio.",
  "Uma página só funciona para ofertas simples e serviços únicos. Várias páginas funcionam melhor para quem tem muitos serviços e quer aparecer no Google para cada um.",
  "#criacaodesites #webdesign #landingpage #empreendedorismo #negocios",
  "O formato certo é o que combina com a sua oferta.",
  [("<p>Site de <b>uma página só</b> ou com <b>várias páginas</b>?</p><p>Depende do seu negócio.</p>",
    [stat("1", "Página", "tudo em sequência", black=False, color="blue", size=200),
     stat("5+", "Páginas", "um tema por página", size=170)]),
   ("<p><b>Uma página só:</b> tudo em sequência, rolando para baixo. Rápido de ler e direto ao ponto.</p>",
    [lista("Bom para", ["Serviço único", "Profissional liberal", "Oferta simples"])]),
   ("<p><b>Várias páginas:</b> cada serviço ganha sua própria página, com mais espaço para explicar.</p>",
    [lista("Bom para", ["Muitos serviços", "Empresas maiores", "Conteúdo e blog"])]),
   ("<p>No Google, <b>uma página por serviço</b> ajuda cada serviço a aparecer na busca certa.</p>",
    [texto("Exemplo", 'suaempresa.com.br/<span class=coral>manutencao</span><br>suaempresa.com.br/<span class=coral>instalacao</span>', black=True, fs=32)]),
   ("<p>Dá para começar com uma página e <b>crescer depois</b>, conforme o negócio pede.</p>",
    [fluxo("Evolução", ["Uma página", "Páginas de serviço", "Blog"])]),
   ])

P("titulo-do-site-que-prende", "site",
  "O título do seu site tem 3 segundos para dizer o que você faz.",
  "Diga o que você faz, para quem e qual o benefício, em uma frase. Nada de bem-vindo ao nosso site.",
  "#copywriting #criacaodesites #marketingdigital #empreendedorismo #negocios",
  "Leia o título do seu site agora. Ele passa no teste?",
  [("<p>O título do seu site tem poucos segundos para dizer <b>o que você faz</b>.</p>",
    [texto("Fraco", '"Bem-vindo ao nosso site"', black=True, fs=36),
     texto("Forte", '"<span class=coral>Contabilidade</span> para pequenas empresas, sem burocracia"', fs=30)]),
   ("<p>A fórmula: <b>o que você faz</b> + <b>para quem</b> + <b>qual o benefício</b>.</p>",
    [fluxo("Fórmula", ["O que você faz", "Para quem", "Benefício"])]),
   ("<p>Evite frases genéricas que servem para qualquer empresa.</p>",
    [nao("Evite", ["Bem-vindo ao nosso site", "Qualidade e excelência", "Soluções inovadoras"])]),
   ("<p>Abaixo do título, um subtítulo curto explica <b>como</b> e um botão leva ao próximo passo.</p>",
    [lista("Estrutura do topo", ["Título", "Subtítulo", "Botão de ação"])]),
   ("<p>O teste: mostre o título para alguém de fora. Se a pessoa não souber dizer o que você faz, <b>reescreva</b>.</p>",
    [texto("Teste", 'A pessoa entendeu <span class=coral>o que você faz</span>?', black=True, fs=42)]),
   ])

P("fotos-reais-no-site", "site",
  "Foto de banco de imagem ou foto real? Para o seu site, a resposta faz diferença.",
  "Fotos reais da equipe, do espaço e do trabalho mostram quem está por trás da marca. Banco de imagem serve para complementar, não para substituir.",
  "#criacaodesites #fotografia #marcapessoal #empreendedorismo #negocios",
  "Uma boa foto sua vale mais do que dez fotos genéricas.",
  [("<p>Foto de <b>banco de imagem</b> ou foto <b>real</b>?</p><p>Para o seu site, faz diferença.</p>",
    [texto("Banco de imagem", "Sorrisos genéricos que aparecem em mil sites.", black=True, fs=30),
     texto("Foto real", 'A sua equipe, o seu espaço, <span class=coral>o seu trabalho</span>.', fs=30)]),
   ("<p>Fotos reais mostram que existe <b>gente de verdade</b> por trás da marca.</p>",
    [lista("Fotos que valem a pena", ["Você e a equipe", "O espaço", "Trabalhos feitos", "Bastidores"])]),
   ("<p>Não precisa de estúdio: celular, <b>luz natural</b> e fundo limpo já resolvem muito.</p>",
    [lista("Dicas", ["Luz natural", "Fundo limpo", "Celular na horizontal", "Várias opções"])]),
   ("<p>Banco de imagem pode entrar como <b>complemento</b>, em ilustrações e fundos, nunca no lugar da sua equipe.</p>",
    [cinza("Evite no banco", ["Equipe falsa", "Cliente falso", "Escritório que não é seu"])]),
   ("<p>Antes de subir, <b>comprima</b> as fotos para o site continuar rápido.</p>",
    [texto("Leveza", 'Foto boa e <span class=coral>leve</span>: formato WebP.', black=True, fs=40)]),
   ])

P("perfil-da-empresa-no-google", "site",
  "Perfil da Empresa no Google: o cadastro gratuito que coloca você no Maps.",
  "Nome, categoria, endereço, horário, fotos, site e avaliações. Um cadastro bem feito aparece na busca local e no Google Maps.",
  "#googlemeunegocio #perfildaempresa #googlemaps #marketinglocal #negocios",
  "Cadastro gratuito, visibilidade local.",
  [("<p><b>Perfil da Empresa no Google:</b> o cadastro gratuito que coloca você no Maps.</p>",
    [aviso("Google Maps", "e na busca da sua região", "📍", black=False, cor=AZUL),
     stat("R$ 0", "Custo", "cadastro gratuito", size=150)]),
   ("<p>Preencha tudo: <b>nome, categoria, endereço, telefone e horário</b>.</p>",
    [lista("Dados básicos", ["Nome", "Categoria", "Endereço", "Telefone", "Horário"], fs=27)]),
   ("<p>Adicione <b>fotos reais</b> e o link do seu <b>site</b>.</p>",
    [lista("Complete com", ["Fotos do espaço", "Fotos do trabalho", "Link do site"])]),
   ("<p>Peça <b>avaliações</b> para clientes satisfeitos e responda todas, inclusive as negativas.</p>",
    [lista("Avaliações", ["Peça depois do atendimento", "Responda todas", "Com educação"])]),
   ("<p>Mantenha atualizado: horário de feriado, serviços novos e fotos recentes.</p>",
    [fluxo("Rotina", ["Atualizar horários", "Postar fotos", "Responder avaliações"])]),
   ])

P("como-responder-avaliacoes-no-google", "site",
  "Como responder avaliações no Google, inclusive as negativas.",
  "Agradeça as positivas pelo nome, responda as negativas com calma e leve a conversa para o privado. Quem lê a resposta é o próximo cliente.",
  "#avaliacoes #googlemeunegocio #atendimento #reputacao #negocios",
  "Quem lê a sua resposta é o próximo cliente.",
  [("<p>Quem lê a resposta a uma avaliação não é só quem avaliou.</p><p>É o <b>próximo cliente</b>.</p>",
    [texto("Avaliação", '★★★★★<div class=sub>E a sua resposta aparece logo abaixo</div>', black=True, fs=46)]),
   ("<p><b>Positiva:</b> agradeça pelo nome e cite algo específico do atendimento.</p>",
    [texto("Exemplo", '"Obrigado, Ana! Foi um prazer cuidar do <span class=coral>seu projeto</span>."', fs=34)]),
   ("<p><b>Negativa:</b> responda com calma, reconheça o problema e ofereça uma solução.</p>",
    [lista("Resposta negativa", ["Sem discutir", "Reconheça o problema", "Ofereça solução"], icon="→")]),
   ("<p>Leve os detalhes para o <b>privado</b>: WhatsApp ou telefone.</p>",
    [texto("Exemplo", '"Sentimos muito. Pode nos chamar no WhatsApp para <span class=coral>resolvermos</span>?"', black=True, fs=32)]),
   ("<p>Nunca responda no calor do momento. <b>Leia, espere, responda.</b></p>",
    [fluxo("Na negativa", ["Leia", "Espere", "Responda"])]),
   ])

P("formulario-de-contato-que-funciona", "site",
  "Formulário de contato com 10 campos? Menos é mais.",
  "Peça só o necessário para o primeiro contato: nome, telefone e mensagem. O resto você descobre na conversa.",
  "#criacaodesites #formulario #conversao #marketingdigital #negocios",
  "Quanto mais fácil o primeiro passo, mais gente dá.",
  [("<p>Formulário de contato com 10 campos?</p><p>Para o primeiro contato, <b>menos é mais</b>.</p>",
    [nao("Formulário longo", ["CPF", "Endereço completo", "Data de nascimento", "Como nos conheceu"], fs=26),
     lista("Formulário curto", ["Nome", "WhatsApp", "Mensagem"])]),
   ("<p>Peça só o necessário: <b>nome, telefone e uma mensagem</b>. O resto você descobre na conversa.</p>",
    [lista("O essencial", ["Nome", "WhatsApp", "Mensagem"])]),
   ("<p>O botão diz o que acontece: <b>\"Quero meu orçamento\"</b> em vez de \"Enviar\".</p>",
    [pilula("Botão", "Quero meu orçamento", "Em vez de Enviar")]),
   ("<p>Depois do envio, mostre uma <b>confirmação</b> e diga em quanto tempo você responde.</p>",
    [texto("Confirmação", '"Recebemos! Respondemos <span class=coral>ainda hoje</span> pelo WhatsApp."', black=True, fs=34)]),
   ("<p>E teste de verdade: envie uma mensagem e confira se ela <b>chega</b>.</p>",
    [fluxo("Teste", ["Preencha", "Envie", "Confira se chegou"])]),
   ])

P("perguntas-frequentes-no-site", "site",
  "A página de perguntas frequentes responde o cliente antes de ele perguntar.",
  "Reúna as dúvidas que chegam no WhatsApp, responda em poucas linhas e coloque perto do botão de contato.",
  "#criacaodesites #atendimento #conversao #empreendedorismo #negocios",
  "Cada dúvida respondida é uma barreira a menos.",
  [("<p>A seção de <b>perguntas frequentes</b> responde o cliente antes de ele perguntar.</p>",
    [lista("Perguntas frequentes", ["Quanto custa?", "Quanto tempo leva?", "Atende online?"], icon="?")]),
   ("<p>De onde tirar as perguntas: do seu <b>WhatsApp</b>. As dúvidas que se repetem são as que entram.</p>",
    [fluxo("Origem", ["Dúvidas no WhatsApp", "As mais repetidas", "Perguntas frequentes"])]),
   ("<p>Respostas <b>curtas</b>, de 2 a 3 linhas, em linguagem simples.</p>",
    [lista("Boas respostas", ["Curtas", "Diretas", "Sem jargão"])]),
   ("<p>Inclua as dúvidas que <b>travam a decisão</b>: prazo, forma de pagamento, garantia, como funciona.</p>",
    [atencao("Não pode faltar", ["Prazo", "Pagamento", "Como funciona", "O que está incluído"])]),
   ("<p>Coloque a seção <b>perto do botão de contato</b>: dúvida resolvida, decisão tomada.</p>",
    [fluxo("Posição", ["Serviços", "Perguntas frequentes", "Botão de contato"])]),
   ])

P("como-montar-um-portfolio", "site",
  "Como montar um portfólio que mostra o seu trabalho do jeito certo.",
  "Selecione os melhores trabalhos, conte o contexto de cada um e mostre o antes e depois, sempre com autorização do cliente.",
  "#portfolio #criacaodesites #marcapessoal #empreendedorismo #negocios",
  "Mostre menos trabalhos, e melhores.",
  [("<p>Portfólio não é depósito de trabalhos.</p><p>É uma <b>seleção</b> que mostra o que você faz de melhor.</p>",
    [texto("Portfólio", 'Menos trabalhos, <span class=coral>mais bem escolhidos</span>.', fs=40)]),
   ("<p>Escolha de <b>6 a 10</b> trabalhos que representam o tipo de cliente que você quer atrair.</p>",
    [lista("Seleção", ["Os melhores", "Os mais recentes", "O cliente que você quer"])]),
   ("<p>Para cada trabalho, conte o <b>contexto</b>: o desafio, o que você fez e o que mudou.</p>",
    [fluxo("Cada projeto", ["Desafio", "O que você fez", "O que mudou"])]),
   ("<p>Quando fizer sentido, mostre o <b>antes e depois</b>.</p>",
    [texto("Antes", "Como era", black=True, fs=40), texto("Depois", '<span class=coral>Como ficou</span>', fs=40)]),
   ("<p>Sempre com <b>autorização</b> do cliente para mostrar o trabalho e o nome dele.</p>",
    [texto("Regra", 'Peça <span class=coral>autorização</span> antes de publicar.', black=True, fs=40)]),
   ])

P("site-para-clinicas-e-consultorios", "site",
  "Clínicas e consultórios: o que o site precisa ter para o paciente agendar.",
  "Especialidades, equipe com registro profissional, convênios, localização e agendamento fácil. Sempre dentro das normas do conselho da profissão.",
  "#clinica #consultorio #criacaodesites #marketingmedico #saude",
  "Paciente que confia, agenda.",
  [("<p>Clínicas e consultórios: o que o site precisa ter para o paciente <b>agendar</b>.</p>",
    [aviso("Paciente", "pesquisa antes de agendar", "🔎", black=False, cor=AZUL),
     lista("Essencial", ["Especialidades", "Equipe", "Agendamento"], fs=28)]),
   ("<p><b>Especialidades e serviços</b>, explicados de forma simples.</p>",
    [lista("Serviços", ["Especialidades", "Exames e procedimentos", "Atendimento online"])]),
   ("<p><b>Equipe</b> com foto, formação e número do registro profissional.</p>",
    [lista("Equipe", ["Foto", "Formação", "Registro profissional"])]),
   ("<p><b>Convênios, localização e horários</b>, fáceis de achar.</p>",
    [lista("Informações", ["Convênios aceitos", "Mapa", "Horários", "Estacionamento"])]),
   ("<p>Agendamento fácil e comunicação <b>dentro das normas</b> do conselho de cada profissão, sem promessa de resultado.</p>",
    [texto("Ética", 'Informar com clareza, <span class=coral>sem prometer resultado</span>.', black=True, fs=38)]),
   ])

P("site-para-restaurantes", "site",
  "Restaurante precisa de site? Veja o que ele resolve.",
  "Cardápio atualizado, horários, localização, reservas e delivery em um só lugar, sem depender só das plataformas de entrega.",
  "#restaurante #gastronomia #criacaodesites #delivery #negocios",
  "O cliente com fome não quer procurar informação.",
  [("<p>Restaurante precisa de site?</p><p>Veja o que ele resolve.</p>",
    [lista("No site", ["Cardápio", "Horários", "Localização", "Reservas"], fs=30),
     stat("🍽", "Cliente com fome", "quer informação rápida", black=False, color="blue", size=140)]),
   ("<p><b>Cardápio atualizado</b>, com fotos reais dos pratos e preços.</p>",
    [lista("Cardápio", ["Fotos reais", "Preços", "Opções especiais"])]),
   ("<p><b>Horários e localização</b> fáceis de achar, com mapa e estacionamento.</p>",
    [lista("Como chegar", ["Mapa", "Horários", "Estacionamento"])]),
   ("<p><b>Reservas e delivery</b>: botão de WhatsApp e link direto para pedir.</p>",
    [fluxo("Pedido", ["Cardápio", "WhatsApp ou link", "Pedido feito"])]),
   ("<p>Com site próprio, você não depende <b>só</b> das plataformas de entrega para ser encontrado.</p>",
    [texto("Canal próprio", 'Seu cliente <span class=coral>direto com você</span>.', black=True, fs=42)]),
   ])

P("site-para-negocio-local", "site",
  "Eletricista, oficina, salão: negócio local também precisa de site.",
  "Quem procura um serviço perto de casa pesquisa no Google. Site com serviços, região atendida e WhatsApp coloca você na conversa.",
  "#negociolocal #criacaodesites #seolocal #prestadordeservicos #empreendedorismo",
  "Quem procura perto de casa precisa encontrar você.",
  [("<p>Eletricista, oficina, salão: <b>negócio local</b> também precisa de site.</p>",
    [texto("A busca", '"eletricista em <span class=coral>[sua cidade]</span>"', black=True, fs=38)]),
   ("<p>Quem procura um serviço perto de casa <b>pesquisa no Google</b>. Seu site precisa estar lá.</p>",
    [fluxo("Jornada", ["Pesquisa no Google", "Seu site", "WhatsApp"])]),
   ("<p>Diga claramente a <b>região que você atende</b>: cidade e bairros.</p>",
    [lista("Região atendida", ["Cidade", "Bairros", "Raio de atendimento"])]),
   ("<p>Mostre <b>trabalhos reais</b> e avaliações de clientes da região.</p>",
    [lista("Confiança", ["Fotos de trabalhos", "Avaliações", "Tempo de experiência"])]),
   ("<p>Junte o site com o <b>Perfil da Empresa no Google</b> para aparecer também no Maps.</p>",
    [aviso("Site + Maps", "presença local completa", "📍", black=False, cor=AZUL)]),
   ])

P("link-na-bio-leve-para-o-site", "site",
  "O link na bio é o espaço mais valioso do seu Instagram. Para onde ele leva?",
  "Um link na bio que leva para o seu site organiza a informação e aproxima o seguidor do contato.",
  "#linknabio #instagramparanegocios #criacaodesites #marketingdigital #negocios",
  "Aproveite o único link clicável do seu perfil.",
  [("<p>O link na bio é o espaço mais valioso do seu Instagram.</p><p>Para onde ele leva?</p>",
    [pilula("Bio", "🔗 suaempresa.com.br", "O único link fixo do perfil")]),
   ("<p>Quem clica já está <b>interessado</b>. Não deixe essa pessoa perdida.</p>",
    [fluxo("Quem clica", ["Viu o conteúdo", "Clicou no link", "Precisa achar o próximo passo"])]),
   ("<p>Levando para o site, a pessoa encontra <b>serviços, provas e contato</b> em um lugar organizado.</p>",
    [lista("No site", ["Serviços", "Depoimentos", "Contato"])]),
   ("<p>Se usar uma página de vários links, coloque o <b>site em primeiro</b> e evite dezenas de botões.</p>",
    [cinza("Evite", ["Links demais", "Links quebrados", "Sem destaque"]),
     lista("Prefira", ["Site em primeiro", "Poucos links", "Um objetivo"])]),
   ("<p>E chame para o link nos posts: <b>\"link na bio\"</b> funciona quando existe um motivo para clicar.</p>",
    [texto("Chamada", '"Veja os serviços completos no <span class=coral>link da bio</span>."', black=True, fs=36)]),
   ])

P("seo-local-cidade-e-servico", "site",
  "Quer aparecer no Google na sua cidade? Fale o nome da cidade no site.",
  "Serviço mais cidade no título, nas páginas e no Perfil da Empresa. É assim que o Google entende onde você atende.",
  "#seolocal #seo #google #criacaodesites #negocios",
  "Diga ao Google o que você faz e onde.",
  [("<p>Quer aparecer no Google na sua cidade?</p><p>Então <b>fale o nome da cidade</b> no site.</p>",
    [texto("Busca", '"dentista em <span class=coral>Campinas</span>"', black=True, fs=40),
     fluxo("Combinação", ["Serviço", "Cidade"])]),
   ("<p>O Google precisa entender <b>o que você faz e onde</b>. Serviço + cidade é a combinação que as pessoas buscam.</p>",
    [texto("Fórmula", '<span class=blue>Serviço</span> + <span class=coral>cidade</span>', fs=48)]),
   ("<p>Use a combinação no <b>título da página</b>, nos textos e nas descrições das fotos, de forma natural.</p>",
    [lista("Onde usar", ["Título da página", "Textos", "Descrição das fotos"])]),
   ("<p>Coloque endereço, telefone e região atendida no <b>rodapé</b>, iguais aos do Perfil da Empresa.</p>",
    [lista("Consistência", ["Mesmo nome", "Mesmo endereço", "Mesmo telefone"])]),
   ("<p>Nada de repetir a cidade vinte vezes: escreva para <b>pessoas</b>, não para robôs.</p>",
    [texto("Regra", 'Natural para quem lê, <span class=coral>claro para o Google</span>.', black=True, fs=38)]),
   ])

P("blog-na-empresa-vale-a-pena", "site",
  "Blog no site da empresa ainda vale a pena?",
  "Vale quando responde dúvidas reais dos clientes. Cada artigo pode aparecer no Google e trazer visitas para o seu site.",
  "#blog #seo #marketingdeconteudo #criacaodesites #negocios",
  "Cada dúvida respondida é uma porta de entrada.",
  [("<p>Blog no site da empresa <b>ainda vale a pena</b>?</p><p>Depende de como você usa.</p>",
    [texto("Blog que funciona", 'Responde <span class=coral>dúvidas reais</span> dos clientes.', fs=40)]),
   ("<p>Cada artigo que responde uma dúvida pode <b>aparecer no Google</b> quando alguém pesquisar aquilo.</p>",
    [fluxo("Como gera visita", ["Dúvida do cliente", "Artigo no blog", "Visita no site"])]),
   ("<p>De onde tirar os temas: perguntas do WhatsApp, dos atendimentos e dos comentários.</p>",
    [lista("Fontes de temas", ["WhatsApp", "Atendimentos", "Comentários", "Perguntas frequentes"])]),
   ("<p>Todo artigo termina com um <b>próximo passo</b>: falar com você.</p>",
    [lista("Estrutura", ["Pergunta no título", "Resposta clara", "Botão de contato"])]),
   ("<p>Constância vale mais que volume: poucos artigos bons, publicados com regularidade.</p>",
    [texto("Ritmo", 'Poucos, <span class=coral>bons</span> e constantes.', black=True, fs=44)]),
   ])

P("o-que-preparar-antes-de-pedir-um-site", "site",
  "Vai pedir um site? Separe estes materiais antes.",
  "Logo, fotos reais, lista de serviços, dúvidas frequentes, contatos e domínio. Com isso em mãos, o projeto anda mais rápido.",
  "#criacaodesites #briefing #empreendedorismo #negocios #sitesprofissionais",
  "Material organizado, site mais rápido.",
  [("<p>Vai pedir um site?</p><p>Separe estes <b>materiais</b> antes.</p>",
    [stat("6", "Itens", "para ter em mãos", size=200)]),
   ("<p><b>Identidade:</b> logo, cores e fontes que você já usa.</p>",
    [lista("Identidade", ["Logo", "Cores", "Fontes"])]),
   ("<p><b>Conteúdo:</b> lista de serviços, diferenciais e as dúvidas que os clientes mais fazem.</p>",
    [lista("Conteúdo", ["Serviços", "Diferenciais", "Dúvidas frequentes"])]),
   ("<p><b>Fotos:</b> equipe, espaço e trabalhos, de preferência reais.</p>",
    [lista("Fotos", ["Equipe", "Espaço", "Trabalhos"])]),
   ("<p><b>Contatos e acessos:</b> WhatsApp, e-mail, endereço, redes sociais e o domínio, se já tiver.</p>",
    [lista("Contatos", ["WhatsApp", "E-mail", "Endereço", "Redes sociais", "Domínio"], fs=27)]),
   ])

P("identidade-visual-no-site", "site",
  "Seu site, seu Instagram e seu cartão parecem da mesma empresa?",
  "Mesmas cores, mesmas fontes e mesmo tom de voz em todos os lugares. Consistência passa profissionalismo.",
  "#identidadevisual #branding #criacaodesites #marketingdigital #negocios",
  "A marca é reconhecida pela repetição.",
  [("<p>Seu site, seu Instagram e seu cartão parecem da <b>mesma empresa</b>?</p>",
    [lista("Pontos de contato", ["Site", "Instagram", "Cartão", "WhatsApp"], icon="→")]),
   ("<p><b>Cores:</b> escolha de 2 a 3 cores principais e use sempre as mesmas.</p>",
    [texto("Paleta", '<span style="color:#4f5dff">■</span> <span class=coral>■</span> <span style="color:#fff">■</span>&nbsp; 2 a 3 cores fixas', black=True, fs=40)]),
   ("<p><b>Fontes:</b> uma para títulos e outra para textos. Não mais que isso.</p>",
    [lista("Fontes", ["Uma para títulos", "Uma para textos"])]),
   ("<p><b>Tom de voz:</b> o jeito de falar precisa ser o mesmo no site e nas redes.</p>",
    [texto("Tom de voz", 'Mesmo jeito de falar <span class=coral>em todo lugar</span>.', fs=40)]),
   ("<p>Consistência faz a pessoa <b>reconhecer</b> a sua marca antes mesmo de ler o nome.</p>",
    [fluxo("Resultado", ["Repetição", "Reconhecimento", "Confiança"])]),
   ])

P("site-institucional-ou-loja-virtual", "site",
  "Site institucional ou loja virtual? Entenda qual o seu negócio precisa.",
  "O institucional apresenta a empresa e leva ao contato. A loja virtual vende direto, com carrinho, pagamento e estoque.",
  "#ecommerce #lojavirtual #criacaodesites #empreendedorismo #negocios",
  "O formato certo depende de como você vende.",
  [("<p>Site institucional ou <b>loja virtual</b>?</p><p>Entenda qual o seu negócio precisa.</p>",
    [texto("Institucional", 'Apresenta e leva ao <span class=blue>contato</span>.', black=True, fs=34),
     texto("Loja virtual", 'Vende <span class=coral>direto</span>, com carrinho.', fs=34)]),
   ("<p><b>Institucional:</b> ideal para serviços, em que a venda acontece numa conversa ou orçamento.</p>",
    [lista("Institucional", ["Serviços", "Orçamento", "Agendamento"])]),
   ("<p><b>Loja virtual:</b> ideal para produtos com preço definido, com carrinho, pagamento e frete.</p>",
    [lista("Loja virtual", ["Carrinho", "Pagamento online", "Frete", "Estoque"])]),
   ("<p>Loja virtual exige mais <b>operação</b>: fotos de cada produto, estoque atualizado e envio.</p>",
    [atencao("Operação da loja", ["Fotos de produto", "Estoque", "Envio", "Trocas"])]),
   ("<p>Dá para começar com o institucional e um <b>catálogo</b>, e evoluir para loja quando fizer sentido.</p>",
    [fluxo("Evolução", ["Institucional", "Catálogo", "Loja virtual"])]),
   ])

# =============================================================== IA NA PRÁTICA (18)

P("prompt-com-papel-definido", "ia",
  "Comece o prompt dizendo quem a IA deve ser. A resposta muda.",
  "Definir um papel, como consultor de vendas ou revisor, ajusta o vocabulário, o foco e o nível da resposta.",
  "#prompt #inteligenciaartificial #chatgpt #produtividade #ia",
  "Teste o mesmo pedido com e sem papel e compare.",
  [("<p>Comece o prompt dizendo <b>quem</b> a IA deve ser.</p><p>A resposta muda.</p>",
    [texto("Sem papel", '"Me dê dicas de vendas."', black=True, fs=36),
     texto("Com papel", '"Você é um <span class=coral>consultor de vendas</span> para pequenas empresas..."', fs=30)]),
   ("<p>O papel ajusta o <b>vocabulário</b>, o foco e o nível de profundidade da resposta.</p>",
    [lista("O papel define", ["Vocabulário", "Foco", "Profundidade"])]),
   ("<p>Exemplos de papéis úteis no dia a dia de um negócio:</p>",
    [lista("Papéis", ["Consultor de vendas", "Revisor de textos", "Analista financeiro", "Cliente exigente"], icon="→")]),
   ("<p>Combine o papel com o <b>contexto</b> do seu negócio.</p>",
    [copie('"Você é um revisor. Meu público é <span class=coral>[público]</span>. Revise este texto: [texto]."')]),
   ("<p>Lembre: o papel melhora o foco, mas <b>não transforma</b> a IA em especialista. Confira o que for importante.</p>",
    [texto("Atenção", 'Papel ajuda. <span class=coral>Checagem continua.</span>', black=True, fs=42)]),
   ])

P("prompt-com-exemplos", "ia",
  "Quer uma resposta no seu estilo? Mostre um exemplo para a IA.",
  "Dar 1 a 3 exemplos do resultado que você quer é o jeito mais rápido de acertar o formato e o tom.",
  "#prompt #inteligenciaartificial #chatgpt #produtividade #ia",
  "Um bom exemplo vale mais que um parágrafo de instruções.",
  [("<p>Quer uma resposta no seu estilo?</p><p><b>Mostre um exemplo</b> para a IA.</p>",
    [texto("Técnica", 'Dê <span class=coral>1 a 3 exemplos</span> do resultado que você quer.', fs=38)]),
   ("<p>Em vez de explicar o formato, <b>mostre</b>: a IA copia a estrutura, o tamanho e o tom.</p>",
    [lista("A IA copia", ["Estrutura", "Tamanho", "Tom"])]),
   ("<p>Exemplo de pedido:</p>",
    [copie('"Escreva 5 legendas no mesmo estilo destas: <span class=coral>[exemplo 1]</span>, <span class=coral>[exemplo 2]</span>."')]),
   ("<p>Use exemplos <b>variados</b>, senão a IA repete sempre a mesma coisa.</p>",
    [lista("Bons exemplos", ["Variados", "Curtos", "Do jeito que você quer"])]),
   ("<p>Funciona para legendas, e-mails, descrições de produto, respostas de atendimento e muito mais.</p>",
    [lista("Onde usar", ["Legendas", "E-mails", "Descrições", "Atendimento"])]),
   ])

P("ia-para-responder-avaliacoes", "ia",
  "Use a IA para rascunhar respostas às avaliações dos clientes.",
  "Dê o contexto, peça um tom educado e personalize antes de publicar. Nunca responda com texto genérico igual para todos.",
  "#avaliacoes #inteligenciaartificial #atendimento #reputacao #negocios",
  "A IA rascunha. A resposta final tem que ter a sua cara.",
  [("<p>Use a IA para rascunhar respostas às <b>avaliações</b> dos clientes.</p>",
    [fluxo("Processo", ["Avaliação", "Rascunho da IA", "Sua revisão"])]),
   ("<p>Dê o contexto: o que aconteceu, o tom da sua marca e o que você pode oferecer.</p>",
    [copie('"Escreva uma resposta educada para esta avaliação. Tom: <span class=coral>[tom]</span>. Avaliação: [texto]."')]),
   ("<p>Para avaliações negativas, peça uma resposta que <b>reconheça</b> o problema e leve para o privado.</p>",
    [lista("Na negativa", ["Reconhecer", "Pedir desculpas", "Levar para o privado"])]),
   ("<p><b>Personalize</b> antes de publicar: nome do cliente e um detalhe do atendimento.</p>",
    [atencao("Antes de publicar", ["Nome do cliente", "Detalhe real", "Sem texto genérico"])]),
   ("<p>Nunca publique a mesma resposta para todo mundo. Quem lê percebe.</p>",
    [texto("Regra", 'Cada avaliação, <span class=coral>uma resposta única</span>.', black=True, fs=40)]),
   ])

P("ia-para-roteiro-de-reels", "ia",
  "Travou no roteiro do reels? Use a IA com esta estrutura.",
  "Gancho nos primeiros segundos, desenvolvimento em 3 pontos e chamada para ação no final. A IA rascunha, você adapta ao seu jeito de falar.",
  "#reels #roteiro #inteligenciaartificial #criadordeconteudo #marketingdigital",
  "O roteiro é da IA. A voz é sua.",
  [("<p>Travou no <b>roteiro</b> do reels?</p><p>Use a IA com esta estrutura.</p>",
    [fluxo("Estrutura", ["Gancho", "3 pontos", "Chamada"])]),
   ("<p><b>Gancho:</b> a frase dos primeiros segundos, que faz a pessoa parar de rolar.</p>",
    [copie('"Escreva 5 ganchos curtos para um vídeo sobre <span class=coral>[tema]</span>, para [público]."')]),
   ("<p><b>Desenvolvimento:</b> 3 pontos claros, uma frase cada.</p>",
    [lista("Desenvolvimento", ["Ponto 1", "Ponto 2", "Ponto 3"], icon="→")]),
   ("<p><b>Chamada para ação:</b> o que a pessoa deve fazer depois de assistir.</p>",
    [lista("Chamadas", ["Seguir", "Salvar", "Comentar", "Mandar no direct"])]),
   ("<p>Leia em voz alta e <b>troque as palavras</b> que você não usaria.</p>",
    [texto("Ajuste final", 'Se não é o seu jeito de falar, <span class=coral>reescreva</span>.', black=True, fs=38)]),
   ])

P("ia-para-pesquisar-concorrentes", "ia",
  "Como usar a IA para analisar a concorrência, sem cair em informação inventada.",
  "Cole textos públicos dos concorrentes e peça comparações. Não peça para a IA adivinhar preços ou números.",
  "#concorrencia #inteligenciaartificial #estrategia #empreendedorismo #negocios",
  "A IA organiza. A informação precisa ser real.",
  [("<p>Dá para usar a IA para analisar a <b>concorrência</b>.</p><p>Mas do jeito certo.</p>",
    [lista("Do jeito certo", ["Dados públicos", "Comparação", "Checagem"]),
     nao("Evite", ["Pedir para adivinhar", "Números sem fonte"])]),
   ("<p>Colete o material: textos dos sites, ofertas e comentários <b>públicos</b> dos concorrentes.</p>",
    [lista("Material", ["Textos dos sites", "Ofertas", "Comentários públicos"])]),
   ("<p>Cole e peça uma <b>comparação</b> organizada.</p>",
    [copie('"Compare estes textos em uma tabela: público, promessa, diferenciais e pontos fracos: <span class=coral>[textos]</span>."')]),
   ("<p>Não peça para a IA <b>adivinhar</b> preços, faturamento ou número de clientes. Ela pode inventar.</p>",
    [atencao("Cuidado", ["Preços", "Faturamento", "Número de clientes"])]),
   ("<p>Use o resultado para achar o seu <b>diferencial</b>: o que ninguém está dizendo.</p>",
    [texto("Pergunta final", 'O que <span class=coral>ninguém</span> está dizendo para esse público?', black=True, fs=38)]),
   ])

P("ia-para-emails-profissionais", "ia",
  "E-mail difícil de escrever? A IA faz o primeiro rascunho em segundos.",
  "Diga o objetivo, o destinatário e o tom. Revise nomes, datas e valores antes de enviar.",
  "#email #inteligenciaartificial #produtividade #comunicacao #negocios",
  "Revise sempre nomes, datas e valores.",
  [("<p>E-mail difícil de escrever?</p><p>A IA faz o <b>primeiro rascunho</b> em segundos.</p>",
    [lista("Bons usos", ["Cobrança educada", "Proposta", "Resposta a reclamação", "Follow-up"], icon="→")]),
   ("<p>Diga o <b>objetivo</b>, o destinatário e o tom.</p>",
    [copie('"Escreva um e-mail curto e cordial para <span class=coral>[cliente]</span> lembrando do pagamento de [valor] vencido em [data]."')]),
   ("<p>Peça versões: <b>mais curta</b>, mais formal ou mais direta.</p>",
    [lista("Variações", ["Mais curta", "Mais formal", "Mais direta"])]),
   ("<p>Antes de enviar, confira <b>nomes, datas e valores</b>. É onde a IA mais erra.</p>",
    [atencao("Confira", ["Nomes", "Datas", "Valores", "Anexos"])]),
   ("<p>E-mail bom tem <b>um objetivo</b> e diz claramente o próximo passo.</p>",
    [texto("Regra", 'Um e-mail, <span class=coral>um objetivo</span>.', black=True, fs=44)]),
   ])

P("ia-para-organizar-a-semana", "ia",
  "Semana caótica? Peça para a IA organizar suas tarefas por prioridade.",
  "Liste tudo, peça para separar em urgente, importante e delegável, e transforme em uma agenda por dia.",
  "#produtividade #organizacao #inteligenciaartificial #gestao #ia",
  "Organizar leva 10 minutos. Improvisar leva a semana inteira.",
  [("<p>Semana caótica?</p><p>Peça para a IA <b>organizar</b> as suas tarefas.</p>",
    [fluxo("Da bagunça ao plano", ["Lista solta", "Prioridades", "Agenda da semana"])]),
   ("<p>Primeiro, despeje <b>tudo</b> numa lista, sem ordem.</p>",
    [lista("Lista solta", ["Ligar para cliente", "Enviar proposta", "Pagar fornecedor", "Postar no Instagram"], icon="•", cor="#333", black=True, fs=27)]),
   ("<p>Peça para separar por <b>prioridade</b>.</p>",
    [copie('"Separe estas tarefas em urgente, importante e delegável: <span class=coral>[lista]</span>."')]),
   ("<p>Depois, transforme em uma <b>agenda por dia</b>, respeitando o tempo que você tem.</p>",
    [copie('"Monte uma agenda de segunda a sexta com essas tarefas. Tenho <span class=coral>[horas]</span> livres por dia."')]),
   ("<p>Revise o plano: você conhece os imprevistos do seu negócio. A IA não.</p>",
    [texto("Ajuste", 'A IA propõe. <span class=coral>Você ajusta.</span>', black=True, fs=44)]),
   ])

P("ia-para-aprender-um-assunto-novo", "ia",
  "Use a IA como professora particular para aprender um assunto novo.",
  "Peça explicações simples, exemplos do seu dia a dia e perguntas para testar o que aprendeu. E confira as informações em fontes confiáveis.",
  "#aprendizado #estudos #inteligenciaartificial #produtividade #ia",
  "Aprender nunca foi tão acessível.",
  [("<p>Use a IA como <b>professora particular</b> para aprender um assunto novo.</p>",
    [fluxo("Método", ["Explicação simples", "Exemplo prático", "Teste"])]),
   ("<p>Peça uma explicação <b>simples</b>, como se você nunca tivesse ouvido falar.</p>",
    [copie('"Explique <span class=coral>[assunto]</span> de forma simples, como para quem nunca ouviu falar."')]),
   ("<p>Peça <b>exemplos</b> ligados ao seu dia a dia ou ao seu negócio.</p>",
    [copie('"Dê 3 exemplos de como isso se aplica a <span class=coral>[seu negócio]</span>."')]),
   ("<p>Peça para ela te <b>testar</b> com perguntas e corrigir as suas respostas.</p>",
    [copie('"Me faça 5 perguntas sobre isso, uma por vez, e <span class=coral>corrija</span> minhas respostas."')]),
   ("<p>Para temas importantes, confira em <b>fontes confiáveis</b>: livros, sites oficiais e especialistas.</p>",
    [atencao("Confira em", ["Sites oficiais", "Livros", "Especialistas"])]),
   ])

P("ia-para-traduzir-e-adaptar", "ia",
  "Traduzir não é só trocar palavras. Peça para a IA adaptar.",
  "Diga o público e o país, peça para manter o tom e revise termos técnicos, nomes e valores.",
  "#traducao #inteligenciaartificial #comunicacao #negocios #ia",
  "Para textos importantes, uma revisão humana ainda faz diferença.",
  [("<p>Traduzir não é só trocar palavras.</p><p>Peça para a IA <b>adaptar</b>.</p>",
    [texto("Tradução literal", "Palavra por palavra.", black=True, fs=36),
     texto("Adaptação", 'Faz sentido <span class=coral>para quem lê</span>.', fs=36)]),
   ("<p>Diga o <b>público</b> e o país: português de Portugal e do Brasil, por exemplo, são diferentes.</p>",
    [copie('"Traduza para o inglês dos EUA, para <span class=coral>[público]</span>, mantendo o tom informal."')]),
   ("<p>Peça para manter o <b>tom</b> e adaptar expressões que não existem no outro idioma.</p>",
    [lista("Peça para", ["Manter o tom", "Adaptar expressões", "Ajustar medidas e moedas"])]),
   ("<p>Revise <b>termos técnicos</b>, nomes próprios e valores.</p>",
    [atencao("Revise", ["Termos técnicos", "Nomes próprios", "Valores e datas"])]),
   ("<p>Para contratos e textos jurídicos, a IA ajuda a entender, mas a versão final pede <b>revisão profissional</b>.</p>",
    [texto("Contratos", 'IA para entender, <span class=coral>profissional para assinar</span>.', black=True, fs=36)]),
   ])

P("imagens-com-ia-cuidados", "ia",
  "Vai criar imagens com IA para o seu negócio? Cuidado com estes 4 pontos.",
  "Não use pessoas reais sem autorização, evite marcas de terceiros, confira os termos da ferramenta e deixe claro quando a imagem é gerada.",
  "#imagenscomia #inteligenciaartificial #marketingdigital #design #ia",
  "Criatividade com responsabilidade.",
  [("<p>Vai criar <b>imagens com IA</b> para o seu negócio?</p><p>Cuidado com estes 4 pontos.</p>",
    [stat("4", "Cuidados", "antes de publicar", size=200)]),
   ("<p><b>1.</b> Não use o rosto ou a voz de <b>pessoas reais</b> sem autorização.</p>",
    [nao("Não faça", ["Rosto de pessoa real", "Imitar famosos", "Cliente sem autorização"])]),
   ("<p><b>2.</b> Evite <b>marcas, personagens e obras</b> de terceiros.</p>",
    [nao("Evite", ["Logos de outras marcas", "Personagens", "Estilo de obra específica"])]),
   ("<p><b>3.</b> Leia os <b>termos de uso</b> da ferramenta: alguns planos limitam o uso comercial.</p>",
    [lista("Confira", ["Uso comercial permitido", "Plano contratado", "Direitos da imagem"])]),
   ("<p><b>4.</b> Não use imagem gerada para <b>enganar</b>: produto que não existe, resultado que não aconteceu.</p>",
    [texto("Regra", 'Imagem gerada <span class=coral>não substitui</span> o produto real.', black=True, fs=38)]),
   ])

P("ia-que-le-imagens", "ia",
  "Tire uma foto e pergunte para a IA. Ela lê imagens também.",
  "Notas fiscais, prints, planilhas impressas e cardápios viram texto organizado. Confira números e valores antes de usar.",
  "#inteligenciaartificial #produtividade #multimodal #tecnologia #ia",
  "Confira sempre números e valores.",
  [("<p>Tire uma foto e pergunte para a IA.</p><p>Ela <b>lê imagens</b> também.</p>",
    [aviso("Foto", "vira texto organizado", "📷", black=False, cor=AZUL),
     lista("Exemplos", ["Nota fiscal", "Print", "Cardápio", "Quadro branco"], fs=27)]),
   ("<p>Foto de uma <b>nota ou recibo</b> vira uma lista com itens e valores.</p>",
    [copie('"Transforme esta nota em uma tabela com <span class=coral>item, quantidade e valor</span>."')]),
   ("<p>Foto do <b>quadro branco</b> da reunião vira resumo com tarefas.</p>",
    [copie('"Organize as anotações desta foto em <span class=coral>tarefas e responsáveis</span>."')]),
   ("<p>Print de um <b>erro</b> no computador vira explicação e possível solução.</p>",
    [fluxo("Print de erro", ["Foto da tela", "Explicação", "Passo a passo"])]),
   ("<p>A leitura pode errar: confira sempre <b>números e valores</b>.</p>",
    [atencao("Confira", ["Números", "Valores", "Nomes"])]),
   ])

P("de-contexto-para-a-ia", "ia",
  "A IA não conhece o seu negócio. Dê contexto antes de pedir.",
  "Anexe documentos, descreva o público e explique o objetivo. Quanto melhor o contexto, mais útil a resposta.",
  "#prompt #inteligenciaartificial #chatgpt #produtividade #ia",
  "Contexto bom, resposta boa.",
  [("<p>A IA não conhece o seu negócio.</p><p>Dê <b>contexto</b> antes de pedir.</p>",
    [texto("Sem contexto", "Resposta genérica, que serve para qualquer um.", black=True, fs=32),
     texto("Com contexto", 'Resposta <span class=coral>feita para você</span>.', fs=36)]),
   ("<p>Explique <b>quem é o seu cliente</b>: idade, região, o que ele procura.</p>",
    [lista("Seu cliente", ["Perfil", "Região", "O que procura", "Principais dúvidas"])]),
   ("<p><b>Anexe documentos</b>: tabela de preços, apresentação, textos do site.</p>",
    [lista("Anexe", ["Tabela de preços", "Apresentação", "Textos do site"])]),
   ("<p>Diga o <b>objetivo</b>: vender, informar, responder, convencer.</p>",
    [lista("Objetivo", ["Vender", "Informar", "Responder", "Convencer"], icon="→")]),
   ("<p>Lembre de não anexar <b>dados sensíveis</b> de clientes.</p>",
    [atencao("Não anexe", ["CPF de clientes", "Senhas", "Contratos sigilosos"])]),
   ])

P("roteiro-de-atendimento-para-ia", "ia",
  "Antes de colocar IA no atendimento, escreva o roteiro dela.",
  "Liste as perguntas frequentes, as respostas oficiais, o que ela não pode fazer e quando passar para uma pessoa.",
  "#atendimento #chatbot #inteligenciaartificial #whatsapp #negocios",
  "IA de atendimento boa começa com um roteiro bom.",
  [("<p>Antes de colocar IA no atendimento, escreva o <b>roteiro</b> dela.</p>",
    [stat("4", "Partes", "do roteiro", size=200)]),
   ("<p><b>1. Perguntas frequentes</b> com as respostas oficiais da empresa.</p>",
    [lista("Base", ["Horários", "Serviços", "Preços", "Formas de pagamento"])]),
   ("<p><b>2. Tom de voz:</b> como a empresa fala com o cliente.</p>",
    [texto("Tom", 'Educado, direto e <span class=coral>com a cara da marca</span>.', fs=38)]),
   ("<p><b>3. Proibições:</b> o que ela nunca pode fazer.</p>",
    [nao("Nunca", ["Inventar preço", "Prometer prazo", "Dar desconto sem regra"])]),
   ("<p><b>4. Transferência:</b> quando a conversa deve ir para uma pessoa.</p>",
    [fluxo("Passar para humano quando", ["Reclamação", "Negociação", "Cliente pedir"])]),
   ])

P("5-erros-ao-usar-ia", "ia",
  "5 erros comuns de quem está começando a usar IA.",
  "Pedido vago, confiar sem conferir, colar dados sensíveis, aceitar a primeira resposta e publicar sem revisar.",
  "#inteligenciaartificial #chatgpt #produtividade #dicas #ia",
  "Qual desses você já cometeu?",
  [("<p><b>5 erros</b> comuns de quem está começando a usar IA.</p>",
    [stat("5", "Erros", "fáceis de evitar", size=200)]),
   ("<p><b>1. Pedido vago:</b> \"faz um texto\" gera uma resposta genérica.</p><p><b>2. Confiar sem conferir.</b></p>",
    [nao("Erros 1 e 2", ["Pedido vago", "Confiar sem conferir"])]),
   ("<p><b>3. Colar dados sensíveis</b>, como senhas e dados de clientes.</p>",
    [nao("Erro 3", ["Senhas", "Dados de clientes"])]),
   ("<p><b>4. Aceitar a primeira resposta.</b> Peça ajustes, variações e melhorias.</p><p><b>5. Publicar sem revisar.</b></p>",
    [nao("Erros 4 e 5", ["Primeira resposta", "Publicar sem revisar"])]),
   ("<p>O jeito certo: pedido claro, checagem, dados protegidos, ajustes e revisão final.</p>",
    [lista("Jeito certo", ["Pedido claro", "Checagem", "Dados protegidos", "Ajustes", "Revisão"], fs=27)]),
   ])

P("ia-para-analisar-feedback-de-clientes", "ia",
  "Use a IA para descobrir o que os seus clientes realmente estão dizendo.",
  "Junte comentários, avaliações e mensagens, anonimize e peça para a IA agrupar elogios, reclamações e sugestões.",
  "#feedback #clientes #inteligenciaartificial #gestao #negocios",
  "O cliente já está dizendo o que melhorar. Basta organizar.",
  [("<p>Use a IA para descobrir o que os seus clientes <b>realmente estão dizendo</b>.</p>",
    [fluxo("Processo", ["Juntar comentários", "Agrupar temas", "Decidir melhorias"])]),
   ("<p>Junte <b>avaliações, comentários e mensagens</b> em um só texto.</p>",
    [lista("Fontes", ["Avaliações do Google", "Comentários", "Mensagens"])]),
   ("<p>Antes de colar, <b>anonimize</b>: tire nomes e telefones.</p>",
    [atencao("Anonimize", ["Nomes", "Telefones", "Dados pessoais"])]),
   ("<p>Peça para agrupar por <b>tema</b>.</p>",
    [copie('"Agrupe estes comentários em elogios, reclamações e sugestões, com os <span class=coral>temas mais citados</span>: [texto]."')]),
   ("<p>Use o resultado para decidir <b>o que melhorar primeiro</b>.</p>",
    [texto("Pergunta final", 'Qual reclamação aparece <span class=coral>mais vezes</span>?', black=True, fs=40)]),
   ])

P("checklist-para-revisar-resposta-da-ia", "ia",
  "Checklist de 5 perguntas para revisar qualquer resposta da IA.",
  "Está correto? Está completo? Tem a minha cara? Tem dado sensível? Eu assinaria embaixo?",
  "#inteligenciaartificial #checklist #produtividade #chatgpt #ia",
  "Salve este checklist e use antes de publicar.",
  [("<p>Checklist de <b>5 perguntas</b> para revisar qualquer resposta da IA.</p>",
    [stat("5", "Perguntas", "antes de usar", size=200)]),
   ("<p><b>1. Está correto?</b> Números, datas e nomes conferidos.</p><p><b>2. Está completo?</b></p>",
    [lista("1 e 2", ["Está correto?", "Está completo?"], icon="?")]),
   ("<p><b>3. Tem a minha cara?</b> O tom combina com a minha marca?</p>",
    [lista("3", ["Tem a minha cara?"], icon="?")]),
   ("<p><b>4. Tem dado sensível?</b> Nada de informação de cliente exposta.</p>",
    [lista("4", ["Tem dado sensível?"], icon="?")]),
   ("<p><b>5. Eu assinaria embaixo?</b> Se não, ainda não está pronto.</p>",
    [texto("Pergunta final", 'Eu <span class=coral>assinaria embaixo</span>?', black=True, fs=46)]),
   ])

P("habilidades-para-trabalhar-com-ia", "ia",
  "Quais habilidades valem mais agora que a IA faz parte do trabalho?",
  "Saber pedir, saber avaliar, conhecer o próprio negócio e tomar decisões. A ferramenta muda, essas habilidades ficam.",
  "#inteligenciaartificial #carreira #mercadodetrabalho #produtividade #ia",
  "A ferramenta muda. Essas habilidades ficam.",
  [("<p>Quais habilidades valem mais agora que a IA faz parte do trabalho?</p>",
    [lista("Habilidades", ["Saber pedir", "Saber avaliar", "Conhecer o negócio", "Decidir"])]),
   ("<p><b>Saber pedir:</b> transformar uma necessidade em um pedido claro.</p>",
    [texto("Saber pedir", 'Pedido claro, <span class=coral>resposta útil</span>.', fs=42)]),
   ("<p><b>Saber avaliar:</b> reconhecer quando a resposta está errada, rasa ou fora do tom.</p>",
    [texto("Saber avaliar", 'Distinguir o bom do <span class=coral>só convincente</span>.', black=True, fs=38)]),
   ("<p><b>Conhecer o negócio:</b> a IA não sabe o que o seu cliente sente. Você sabe.</p>",
    [texto("Conhecer o negócio", 'O contexto é <span class=coral>seu</span>.', fs=44)]),
   ("<p><b>Decidir:</b> a IA sugere caminhos. A responsabilidade da escolha continua humana.</p>",
    [fluxo("Divisão", ["A IA sugere", "Você decide"])]),
   ])

P("ia-para-descricao-de-produtos", "ia",
  "Descrição de produto que vende: use a IA com as informações certas.",
  "Dê as características reais, o público e o tom. Peça benefícios, não só especificações, e confira cada dado antes de publicar.",
  "#ecommerce #copywriting #inteligenciaartificial #vendas #negocios",
  "A IA escreve rápido. Os dados têm que ser reais.",
  [("<p>Descrição de produto que vende: use a IA com as <b>informações certas</b>.</p>",
    [texto("Especificação", "Tecido 100% algodão.", black=True, fs=36),
     texto("Benefício", 'Fresco para usar <span class=coral>o dia inteiro</span>.', fs=36)]),
   ("<p>Dê as <b>características reais</b>: material, medidas, uso e diferenciais.</p>",
    [lista("Informe", ["Material", "Medidas", "Como usar", "Diferenciais"])]),
   ("<p>Peça <b>benefícios</b>, não só especificações.</p>",
    [copie('"Com estas características, escreva uma descrição focada em <span class=coral>benefícios</span> para [público]: [dados]."')]),
   ("<p>Peça também uma versão <b>curta</b>, para redes sociais e anúncios.</p>",
    [lista("Versões", ["Descrição completa", "Versão curta", "Título do produto"])]),
   ("<p>Confira cada dado: a IA pode <b>inventar</b> uma característica que o produto não tem.</p>",
    [atencao("Confira", ["Medidas", "Material", "Garantia", "Prazo"])]),
   ])

# =============================================================== TECNOLOGIA E SEGURANÇA (12)

P("o-que-e-llm", "tech",
  "LLM: a sigla por trás do ChatGPT, do Claude e do Gemini.",
  "Modelo de linguagem de grande escala: uma IA treinada com muito texto para prever a próxima palavra e, assim, conversar, resumir e escrever.",
  "#llm #inteligenciaartificial #chatgpt #tecnologia #ia",
  "Agora você sabe o que está por trás da conversa.",
  [("<p><b>LLM:</b> a sigla por trás do ChatGPT, do Claude e do Gemini.</p>",
    [stat("LLM", "Large Language Model", "modelo de linguagem de grande escala", size=150)]),
   ("<p>É uma IA treinada com uma quantidade enorme de <b>texto</b> para entender e gerar linguagem.</p>",
    [texto("Treinamento", 'Muito texto para aprender <span class=coral>padrões da linguagem</span>.', fs=36)]),
   ("<p>No fundo, ela aprende a prever a <b>próxima palavra</b>. Fazendo isso muitas vezes, escreve frases inteiras.</p>",
    [fluxo("Como gera texto", ["Lê o pedido", "Prevê a próxima palavra", "Repete até terminar"])]),
   ("<p>É por isso que ela escreve bem, mas pode <b>errar com confiança</b>: o provável nem sempre é o verdadeiro.</p>",
    [atencao("Por isso", ["Escreve bem", "Pode errar", "Precisa de checagem"])]),
   ("<p>Hoje, muitos LLMs também leem imagens, ouvem áudio e usam ferramentas.</p>",
    [lista("Além de texto", ["Imagens", "Áudio", "Ferramentas"])]),
   ])

P("modelos-de-ia-abertos", "tech",
  "IA aberta e IA fechada: qual a diferença?",
  "Nos modelos abertos, os pesos são publicados e podem rodar em servidores próprios. Nos fechados, o acesso é pelo app ou pela API da empresa.",
  "#inteligenciaartificial #opensource #tecnologia #llm #ia",
  "Cada modelo tem o seu uso.",
  [("<p>IA <b>aberta</b> e IA <b>fechada</b>: qual a diferença?</p>",
    [texto("Aberta", 'Pesos publicados, <span class=blue>roda onde você quiser</span>.', black=True, fs=32),
     texto("Fechada", 'Acesso pelo <span class=coral>app ou pela API</span> da empresa.', fs=32)]),
   ("<p>Nos modelos <b>abertos</b>, a empresa publica os \"pesos\", o resultado do treinamento, e qualquer um pode baixar e rodar.</p>",
    [lista("Modelos abertos", ["Pesos publicados", "Rodam em servidor próprio", "Podem ser ajustados"])]),
   ("<p>Nos modelos <b>fechados</b>, você usa pelo aplicativo ou pela API, e a empresa cuida da infraestrutura.</p>",
    [lista("Modelos fechados", ["Acesso por app ou API", "Infraestrutura da empresa", "Atualizações automáticas"])]),
   ("<p>Vantagem do aberto: <b>controle</b> sobre onde os dados ficam. Custo: exige estrutura técnica.</p>",
    [lista("Aberto", ["Mais controle", "Exige estrutura"]), lista("Fechado", ["Mais prático", "Depende do fornecedor"], black=True)]),
   ("<p>Para a maioria dos pequenos negócios, o fechado é mais prático. O aberto faz sentido quando há exigência forte de privacidade ou personalização.</p>",
    [fluxo("Escolha", ["Qual o seu uso?", "Qual a exigência de privacidade?", "Qual a estrutura técnica?"])]),
   ])

P("o-que-e-data-center", "tech",
  "Todo mundo fala de data center por causa da IA. Mas o que é isso?",
  "Prédios cheios de servidores que guardam dados e rodam sistemas, sites e modelos de IA. Consomem muita energia e água para refrigeração.",
  "#datacenter #inteligenciaartificial #tecnologia #nuvem #energia",
  "Por trás de cada resposta da IA, existe um data center.",
  [("<p>Todo mundo fala de <b>data center</b> por causa da IA.</p><p>Mas o que é isso?</p>",
    [aviso("Data center", "prédio cheio de servidores", "🏢", black=False, cor=AZUL)]),
   ("<p>É um prédio com milhares de <b>servidores</b> que guardam dados e rodam sistemas, sites e aplicativos.</p>",
    [lista("O que roda lá", ["Sites", "Aplicativos", "Nuvem", "Modelos de IA"])]),
   ("<p>A IA exige chips potentes, como <b>GPUs</b>, que consomem muita energia.</p>",
    [texto("IA", 'Chips potentes, <span class=coral>muita energia</span>.', fs=42)]),
   ("<p>Além de energia, data centers precisam de <b>refrigeração</b>, e muitos usam água para isso.</p>",
    [lista("Necessidades", ["Energia", "Refrigeração", "Internet rápida", "Segurança física"])]),
   ("<p>Por isso, a construção de data centers virou tema de <b>economia, energia e meio ambiente</b> em vários países.</p>",
    [fluxo("O debate", ["Mais IA", "Mais data centers", "Mais energia e água"])]),
   ])

P("criptografia-de-ponta-a-ponta", "tech",
  "Criptografia de ponta a ponta: o que ela protege no seu WhatsApp.",
  "Só quem envia e quem recebe consegue ler a mensagem. Mas ela não protege contra golpes nem contra alguém com o seu celular desbloqueado.",
  "#criptografia #whatsapp #seguranca #privacidade #tecnologia",
  "Criptografia protege o caminho. O resto depende de você.",
  [("<p><b>Criptografia de ponta a ponta:</b> o que ela protege no seu WhatsApp.</p>",
    [fluxo("Ponta a ponta", ["Você", "Mensagem embaralhada", "Destinatário"])]),
   ("<p>Só quem envia e quem recebe conseguem <b>ler</b> a mensagem. No caminho, ela fica embaralhada.</p>",
    [texto("No caminho", '<span class=coral>x7#k2!p9@...</span><div class=sub>Ilegível para quem intercepta</div>', black=True, fs=40)]),
   ("<p>No WhatsApp, as conversas pessoais usam criptografia de ponta a ponta <b>por padrão</b>.</p>",
    [lista("Protege", ["Mensagens", "Áudios", "Fotos", "Chamadas"])]),
   ("<p>O que ela <b>não protege</b>: golpes, links falsos e alguém com o seu celular desbloqueado.</p>",
    [nao("Não protege contra", ["Golpes", "Links falsos", "Celular desbloqueado"])]),
   ("<p>Complete a proteção com <b>bloqueio de tela</b> e confirmação em duas etapas.</p>",
    [lista("Complete com", ["Bloqueio de tela", "Duas etapas", "Desconfiança de links"])]),
   ])

P("o-que-e-vpn", "tech",
  "VPN: para que serve e quando vale a pena usar.",
  "A VPN cria um túnel criptografado entre o seu aparelho e a internet. Útil em redes públicas, mas não deixa ninguém anônimo nem impede golpes.",
  "#vpn #seguranca #privacidade #tecnologia #dicas",
  "Ferramenta útil, não mágica.",
  [("<p><b>VPN:</b> para que serve e quando vale a pena usar.</p>",
    [fluxo("VPN", ["Seu aparelho", "Túnel criptografado", "Internet"])]),
   ("<p>A VPN cria um <b>túnel criptografado</b> entre o seu aparelho e um servidor, por onde passa a sua conexão.</p>",
    [texto("Túnel", 'Quem está na mesma rede <span class=coral>não vê</span> o que você acessa.', fs=36)]),
   ("<p>Quando é útil: <b>Wi-Fi público</b>, viagens e acesso remoto aos sistemas da empresa.</p>",
    [lista("Útil em", ["Wi-Fi público", "Viagens", "Acesso remoto à empresa"])]),
   ("<p>O que ela <b>não faz</b>: não te deixa totalmente anônimo e não protege contra golpes ou vírus.</p>",
    [nao("Não faz", ["Anonimato total", "Proteção contra golpes", "Antivírus"])]),
   ("<p>Escolha com cuidado: a empresa da VPN vê o seu tráfego. Prefira serviços <b>conhecidos e transparentes</b>.</p>",
    [atencao("Escolha", ["Empresa conhecida", "Política clara", "Desconfie do gratuito"])]),
   ])

P("o-que-sao-cookies", "tech",
  "Aceitar cookies: o que você está autorizando?",
  "Cookies são pequenos arquivos que os sites guardam no navegador. Alguns são essenciais, outros servem para análise e anúncios.",
  "#cookies #privacidade #lgpd #tecnologia #internet",
  "Na próxima vez, clique em configurar.",
  [("<p>Aceitar cookies: o que você está <b>autorizando</b>?</p>",
    [pilula("Aviso de cookies", "Aceitar todos · Configurar", "O que cada botão significa?")]),
   ("<p>Cookies são <b>pequenos arquivos</b> que o site guarda no seu navegador.</p>",
    [texto("Cookie", 'Um pequeno arquivo que <span class=coral>lembra de você</span>.', fs=40)]),
   ("<p><b>Essenciais:</b> fazem o site funcionar, como manter você logado ou lembrar o carrinho.</p>",
    [lista("Essenciais", ["Login", "Carrinho", "Preferências"])]),
   ("<p><b>Análise e anúncios:</b> acompanham a sua navegação para medir visitas e mostrar propaganda.</p>",
    [atencao("Rastreamento", ["Análise de visitas", "Anúncios", "Perfil de interesses"])]),
   ("<p>Em <b>Configurar</b>, dá para aceitar só os essenciais. E quem tem site precisa oferecer essa escolha.</p>",
    [fluxo("Na prática", ["Configurar", "Só essenciais", "Salvar"])]),
   ])

P("o-que-e-dns", "tech",
  "DNS: a agenda de contatos da internet.",
  "Você digita um nome, o DNS encontra o endereço numérico do servidor. É por isso que o domínio precisa estar configurado para o site aparecer.",
  "#dns #dominio #tecnologia #internet #criacaodesites",
  "Agora você sabe o que acontece quando digita um endereço.",
  [("<p><b>DNS:</b> a agenda de contatos da internet.</p>",
    [texto("Agenda", 'suaempresa.com.br → <span class=coral>203.0.113.10</span>', black=True, fs=36)]),
   ("<p>Computadores se encontram por <b>números</b>, os endereços IP. Nós lembramos de <b>nomes</b>.</p>",
    [texto("Nomes", "suaempresa.com.br", fs=34), texto("Números", '<span class=coral>203.0.113.10</span>', black=True, fs=34)]),
   ("<p>O DNS traduz o nome que você digita no endereço do servidor onde o site está.</p>",
    [fluxo("Na prática", ["Você digita o nome", "O DNS acha o número", "O site abre"])]),
   ("<p>Quando você troca de hospedagem, é no DNS que você <b>aponta</b> o domínio para o novo servidor.</p>",
    [lista("Configurações comuns", ["Apontar o site", "Configurar o e-mail", "Verificar no Google"])]),
   ("<p>Uma mudança no DNS pode levar algumas horas para valer em toda a internet.</p>",
    [texto("Paciência", 'Mudou o DNS? <span class=coral>Pode levar algumas horas.</span>', black=True, fs=36)]),
   ])

P("o-que-e-saas", "tech",
  "SaaS: por que quase todo software agora é assinatura?",
  "Software como serviço: você usa pela internet, paga por mês e não precisa instalar nem atualizar. Em troca, depende do fornecedor.",
  "#saas #tecnologia #software #negocios #empreendedorismo",
  "Revise as suas assinaturas uma vez por mês.",
  [("<p><b>SaaS:</b> por que quase todo software agora é assinatura?</p>",
    [stat("SaaS", "Software as a Service", "software como serviço", size=140)]),
   ("<p>Você usa o programa <b>pela internet</b>, paga por mês ou por ano, e não precisa instalar.</p>",
    [lista("Exemplos", ["E-mail", "Planilhas online", "Sistemas de gestão", "Ferramentas de IA"])]),
   ("<p>Vantagens: <b>atualizações automáticas</b>, acesso de qualquer lugar e começar a usar na hora.</p>",
    [lista("Vantagens", ["Sem instalação", "Sempre atualizado", "Acesso de qualquer lugar"])]),
   ("<p>Cuidados: você <b>depende</b> do fornecedor, e os custos mensais somam.</p>",
    [atencao("Cuidados", ["Dependência do fornecedor", "Custos que se acumulam", "Exportar seus dados"])]),
   ("<p>Dica: revise suas assinaturas todo mês e cancele o que <b>não usa</b>.</p>",
    [fluxo("Revisão mensal", ["Liste as assinaturas", "Veja o uso", "Cancele o que sobra"])]),
   ])

P("golpe-do-boleto-falso", "tech",
  "Golpe do boleto falso: como conferir antes de pagar.",
  "Confira o nome do beneficiário, o valor e o banco emissor antes de confirmar. Na dúvida, peça a segunda via pelo canal oficial.",
  "#golpe #boleto #seguranca #financas #dicas",
  "Dois minutos de conferência evitam o prejuízo.",
  [("<p>Golpe do <b>boleto falso</b>: como conferir antes de pagar.</p>",
    [aviso("Boleto", "confira antes de pagar", "!", cor=CORAL),
     lista("Confira", ["Beneficiário", "Valor", "Banco emissor"], fs=28)]),
   ("<p>O golpista altera o boleto para o dinheiro ir para <b>outra conta</b>, mantendo a aparência original.</p>",
    [texto("Como funciona", 'Mesma aparência, <span class=coral>outro recebedor</span>.', black=True, fs=40)]),
   ("<p>Na tela de pagamento do banco, confira o <b>nome do beneficiário</b>. Tem que ser a empresa que você conhece.</p>",
    [pilula("Tela do banco", "Beneficiário: confira o nome", "Antes de confirmar")]),
   ("<p>Confira também o <b>valor</b> e se o boleto chegou pelo canal de sempre.</p>",
    [atencao("Sinais de alerta", ["Nome diferente", "Valor diferente", "Canal diferente"])]),
   ("<p>Na dúvida, peça a <b>segunda via</b> pelo site ou app oficial da empresa.</p>",
    [fluxo("Na dúvida", ["Não pague", "Acesse o canal oficial", "Emita a segunda via"])]),
   ])

P("whatsapp-clonado-como-evitar", "tech",
  "WhatsApp clonado: o código de 6 dígitos que você nunca deve passar.",
  "O golpista pede o código que chega por SMS para ativar o seu WhatsApp em outro celular. Nunca compartilhe e ative a confirmação em duas etapas.",
  "#whatsapp #golpe #seguranca #tecnologia #dicas",
  "Esse código é só seu. Sempre.",
  [("<p>WhatsApp clonado: o <b>código de 6 dígitos</b> que você nunca deve passar.</p>",
    [pilula("SMS", "Seu código do WhatsApp: ••• •••", "Não compartilhe com ninguém")]),
   ("<p>O golpe: alguém pede o código com uma desculpa, como <b>pesquisa, promoção ou entrega</b>.</p>",
    [atencao("Desculpas comuns", ["Pesquisa", "Promoção", "Entrega", "Cadastro"])]),
   ("<p>Esse código ativa o seu WhatsApp em <b>outro celular</b>. Com ele, o golpista fala com os seus contatos como se fosse você.</p>",
    [fluxo("O golpe", ["Você passa o código", "Conta ativada em outro celular", "Pedidos de dinheiro aos contatos"])]),
   ("<p>Proteja-se: ative a <b>confirmação em duas etapas</b> e nunca compartilhe o código.</p>",
    [lista("Proteção", ["Nunca passar o código", "Confirmação em duas etapas", "E-mail de recuperação"])]),
   ("<p>Se acontecer: reinstale o WhatsApp no seu número, avise seus contatos e procure o suporte do app.</p>",
    [fluxo("Se cair", ["Reinstale o app", "Avise os contatos", "Fale com o suporte"])]),
   ])

P("permissoes-de-aplicativos", "tech",
  "Aquele app de lanterna precisa acessar os seus contatos?",
  "Revise as permissões dos aplicativos: câmera, microfone, localização e contatos só para quem realmente precisa.",
  "#privacidade #celular #seguranca #aplicativos #dicas",
  "Reserve 5 minutos hoje para revisar.",
  [("<p>Aquele app de lanterna precisa acessar os seus <b>contatos</b>?</p>",
    [nao("Permissões suspeitas", ["Contatos", "Microfone", "Localização"]),
     aviso("App de lanterna", "precisa só da lanterna", "🔦", black=False, cor=AZUL)]),
   ("<p>Cada permissão dá ao app acesso a uma parte da sua vida: <b>câmera, microfone, localização, fotos e contatos</b>.</p>",
    [lista("Permissões", ["Câmera", "Microfone", "Localização", "Fotos", "Contatos"], fs=27)]),
   ("<p>A regra: o app só deve ter acesso ao que <b>precisa</b> para funcionar.</p>",
    [texto("Regra", 'Permissão só para <span class=coral>o que faz sentido</span>.', black=True, fs=40)]),
   ("<p>Onde revisar: nas <b>configurações do celular</b>, em privacidade ou permissões.</p>",
    [pilula("Celular", "Configurações → Privacidade", "Permissões por app")]),
   ("<p>Prefira \"<b>somente durante o uso</b>\" para localização e remova apps que você não usa mais.</p>",
    [lista("Boas práticas", ["Localização só durante o uso", "Apagar apps parados", "Revisar a cada mês"])]),
   ])

P("como-criar-uma-senha-forte", "tech",
  "Senha forte não precisa ser impossível de lembrar. Use frases.",
  "Uma frase-senha longa, com palavras aleatórias, é mais forte e mais fácil de lembrar do que uma senha curta cheia de símbolos.",
  "#senhas #seguranca #tecnologia #privacidade #dicas",
  "Troque hoje a senha do seu e-mail principal.",
  [("<p>Senha forte não precisa ser impossível de lembrar.</p><p>Use <b>frases</b>.</p>",
    [texto("Fraca", "Empresa@123", black=True, fs=40),
     texto("Forte", '<span class=coral>cafe-janela-bicicleta-nuvem</span>', fs=30)]),
   ("<p><b>Tamanho</b> pesa muito na força de uma senha. Quanto mais longa, mais difícil de quebrar.</p>",
    [texto("Regra", 'Mais <span class=coral>longa</span> é mais forte.', fs=44)]),
   ("<p>Uma <b>frase-senha</b> com 4 ou mais palavras aleatórias é longa e fácil de lembrar.</p>",
    [lista("Frase-senha", ["4 ou mais palavras", "Sem relação entre elas", "Separadas por hífen"])]),
   ("<p>Evite o óbvio: nome, data de nascimento, nome da empresa e sequências.</p>",
    [nao("Evite", ["Nome e sobrenome", "Datas", "Nome da empresa", "123456"])]),
   ("<p>E nunca repita: uma senha diferente para cada conta, guardada num <b>gerenciador de senhas</b>.</p>",
    [fluxo("Proteção", ["Frase-senha", "Uma por conta", "Gerenciador"])]),
   ])
