"""Conteúdo dos 50 carrosséis do pacote diário (6 notícias + 44 conteúdos perenes).

Cada post tem: slug, cat (news | site | ia | tech), gancho e resumo (usados nas legendas),
tags, fecho (frase do último slide), fonte (opcional) e os slides (texto, cards).
O slide final de chamada para ação é gerado automaticamente pela categoria.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "_base"))
from modelo import (stat, lista, linha, fluxo, aviso, pilula, barras, browser, texto)  # noqa: E402

X = "✕"
VERM = "#c9463d"
CORAL = "#E07A5F"
AZUL = "#7c8cff"

POSTS = []


def P(slug, cat, gancho, resumo, tags, fecho, slides, fonte=""):
    POSTS.append(dict(slug=slug, cat=cat, gancho=gancho, resumo=resumo, tags=tags, fecho=fecho, slides=slides, fonte=fonte))


def nao(label, items, fs=29):
    return lista(label, items, icon=X, cor=VERM, black=True, fs=fs)


def atencao(label, items, fs=29):
    return lista(label, items, icon="!", cor=CORAL, black=True, fs=fs)


def cinza(label, items, fs=29):
    return lista(label, items, icon=X, cor="#333", black=True, fs=fs)


def copie(txt):
    return texto("Copie e adapte", txt, black=True, fs=30)


# =============================================================== NOTÍCIAS (6)

P("tse-deepfake-eleicoes-2026", "news",
  "O TSE definiu o que é deepfake nas eleições de 2026, e a punição pode chegar à cassação.",
  "Propaganda feita com IA precisa de aviso claro. Caricatura e sátira ficam de fora. E nas 72 horas antes da votação, conteúdo sintético novo com candidatos está proibido.",
  "#eleicoes2026 #tse #deepfake #inteligenciaartificial #brasil",
  "Informação é a melhor defesa contra deepfake.",
  [("<p>🔥 <b>BREAKING:</b> o TSE definiu o que é <b>deepfake</b> nas eleições de 2026.</p>"
    "<p>E deixou claro o que pode e o que <b>não pode</b> na propaganda com IA.</p>",
    [stat("5 × 2", "Placar", "no TSE para fixar a regra", size=150),
     aviso("Deepfake", "proibido na propaganda eleitoral", X, cor="#ff8a7a")]),
   ("<p>Para o TSE, deepfake é conteúdo feito ou alterado por IA, com <b>aparência realista</b>, que cria ou muda a imagem, a voz ou a fala de uma pessoa.</p>",
    [atencao("Entra na definição", ["Imagem de uma pessoa", "Voz", "Fala ou manifestação"])]),
   ("<p>Fica <b>fora</b> da definição o que não tenta se passar por registro real:</p>",
    [lista("Não é deepfake", ["Caricaturas", "Montagens satíricas", "Avatares estilizados", "Ajustes técnicos de áudio e imagem"])]),
   ("<p>Toda propaganda feita ou muito alterada por IA precisa <b>avisar, de forma clara</b>, que o conteúdo foi fabricado e qual tecnologia foi usada.</p>",
    [texto("Regra de rotulagem", 'Conteúdo feito com IA precisa de <span class=coral>aviso explícito e em destaque</span>.', fs=40)]),
   ("<p>Das <b>72 horas antes</b> até <b>24 horas depois</b> da votação, fica proibido publicar ou impulsionar conteúdo sintético novo com candidatos, mesmo rotulado.</p>",
    [linha("Janela proibida", [("72h antes", "Proibido publicar conteúdo sintético novo"), ("04/10", "Primeiro turno"), ("24h depois", "A proibição continua")])]),
   ("<p>As punições: sem o aviso, a publicação pode ser <b>removida na hora</b>.</p>"
    "<p>Deepfake para favorecer ou prejudicar candidato pode levar à <b>cassação do registro ou do mandato</b>.</p>",
    [stat("Cassação", "Punição máxima", "do registro ou do mandato", size=110)]),
   ], fonte="TSE, Estado de Minas e Migalhas (setembro/2026)")

P("amd-compra-world-labs", "news",
  "A AMD vai pagar US$ 8,2 bilhões pela startup da Fei-Fei Li.",
  "A World Labs cria IA que entende o mundo físico. Fei-Fei Li vira cientista-chefe da AMD, e é a segunda maior compra da história da empresa.",
  "#amd #inteligenciaartificial #tecnologia #ia #negocios",
  "A disputa da IA já não é só por chips. É por quem entende o mundo real.",
  [("<p>🔥 <b>BREAKING:</b> a AMD vai comprar a <b>World Labs</b>, startup da pesquisadora Fei-Fei Li, por <b>US$ 8,2 bilhões</b>.</p>",
    [stat("US$ 8,2 bi", "Negócio", "pago em ações", size=78),
     texto("Quem compra quem", '<span class=coral>AMD</span> compra a <span class=blue>World Labs</span>', fs=40)]),
   ("<p>O que a World Labs faz: cria modelos de IA que tentam <b>entender o mundo físico</b>, o espaço, os objetos e como eles se relacionam.</p>",
    [lista("Foco da World Labs", ["IA espacial", "Modelos de mundo", "IA física"], icon="✦")]),
   ("<p>Quem é <b>Fei-Fei Li</b>: professora de Stanford e pioneira da visão computacional. Ela criou o <b>ImageNet</b>, base que marcou a história da IA.</p>",
    [texto("Fei-Fei Li na AMD", 'Vice-presidente executiva e <span class=coral>cientista-chefe</span>', fs=42)]),
   ("<p>É a <b>segunda maior compra</b> da história da AMD. A maior foi a Xilinx, por cerca de US$ 50 bilhões, em 2022.</p>",
    [barras("Maiores compras da AMD", [("Xilinx (2022)", 50, "~US$ 50 bi"), ("World Labs (2026)", 8.2, "US$ 8,2 bi")])]),
   ("<p>A compra ainda depende de <b>aprovação regulatória</b> e deve ser concluída até o fim do ano.</p>",
    [fluxo("Próximos passos", ["Anúncio · 28/09", "Aprovação regulatória", "Conclusão até o fim do ano"], destaque=False)]),
   ], fonte="TechCrunch, CNBC e Bloomberg (28/09/2026)")

P("youtube-feed-com-ia", "news",
  "O YouTube vai deixar você montar o seu próprio algoritmo com IA.",
  "Você descreve o que quer assistir e o Gemini cria um feed só seu, numa aba separada da página inicial. A liberação começa em outubro.",
  "#youtube #gemini #inteligenciaartificial #tecnologia #google",
  "Para quem cria conteúdo: o público vai pedir o assunto com as palavras dele. Fale do jeito que o seu cliente pergunta.",
  [("<p>O YouTube vai deixar você <b>montar o seu próprio algoritmo</b>.</p>"
    "<p>É só descrever, com as suas palavras, o que quer assistir.</p>",
    [pilula("Novo feed", "podcasts de 30 min sobre negócios", "Você escreve, o Gemini monta"),
     stat("Gemini", "Por trás", "a IA do Google monta o feed", size=90)]),
   ("<p>Como funciona: você escreve um pedido e o <b>Gemini</b> cria um feed personalizado, que vira uma <b>aba própria</b> na página inicial.</p>",
    [fluxo("Passo a passo", ["Você descreve o feed", "O Gemini interpreta", "Nova aba na página inicial"])]),
   ("<p>Dá para ser bem específico: temas, duração, humor do momento, <b>o que incluir</b> e <b>o que evitar</b>.</p>",
    [lista("O pedido pode ter", ["Tema", "Duração dos vídeos", "Humor do momento", "O que evitar"])]),
   ("<p>O feed normal <b>continua lá</b>. Os feeds personalizados ficam ao lado dele, e você escolhe qual abrir.</p>",
    [texto("Exemplo de abas", 'Início &nbsp;·&nbsp; <span class=coral>Negócios</span> &nbsp;·&nbsp; <span class=blue>Podcasts</span>', black=True, fs=40)]),
   ("<p>A liberação começa em <b>outubro</b>, na web e no celular.</p>",
    [stat("OUT", "Liberação", "na web e no celular", black=False, color="blue", size=170)]),
   ], fonte="TechCrunch (23/09/2026)")

P("google-home-agentes-de-ia", "news",
  "Claude e ChatGPT agora podem controlar a casa inteligente do Google.",
  "O Google Home ganhou um servidor MCP para agentes de IA de fora. Por enquanto, só nos EUA, no plano de US$ 20 por mês, e o agente não destrava portas.",
  "#googlehome #casainteligente #inteligenciaartificial #mcp #tecnologia",
  "Os agentes de IA estão saindo da tela e entrando na casa.",
  [("<p>O Google abriu a casa inteligente para <b>agentes de IA de fora</b>.</p>"
    "<p>Claude, ChatGPT e outros já podem controlar dispositivos do Google Home.</p>",
    [aviso("Google Home", "agora conversa com outros agentes", "🏠", black=False, cor=AZUL),
     lista("Agentes compatíveis", ["Claude", "ChatGPT", "Google Antigravity", "Hermes e OpenClaw"], fs=26)]),
   ("<p>Como: o Google lançou um <b>servidor MCP</b> para o Google Home. MCP é o padrão aberto que conecta agentes de IA a outros serviços.</p>",
    [texto("MCP", 'Model Context Protocol: o <span class=coral>conector</span> entre agentes de IA e aplicativos.', fs=36)]),
   ("<p>O que o agente consegue fazer:</p>",
    [lista("Capacidades", ["Controlar dispositivos", "Resumir o que as câmeras viram", "Acompanhar a atividade da casa", "Criar painéis personalizados"])]),
   ("<p>Os limites: o agente <b>não destrava portas</b>, tem limite de uso, e o Gemini continua como assistente padrão do app.</p>",
    [atencao("Limites", ["Não destrava portas", "Limite de uso", "Gemini segue como padrão"])]),
   ("<p>Quem pode usar: por enquanto, só nos <b>EUA</b>, com o plano <b>Google Home Premium Advanced</b>, de US$ 20 por mês, em acesso antecipado.</p>",
    [stat("US$ 20", "Por mês", "plano Premium Advanced · só EUA", size=110)]),
   ], fonte="TechCrunch (16/09/2026) e Android Police")

P("ray-ban-meta-gen-3", "news",
  "Os novos óculos com IA da Meta chegaram: mais bateria e preço maior.",
  "A Ray-Ban Meta Gen 3 tem até 9 horas de bateria, câmera de 12 MP e vídeo em 3K. Começa em US$ 449, US$ 70 a mais que a geração anterior.",
  "#meta #raybanmeta #oculosinteligentes #tecnologia #inteligenciaartificial",
  "A IA está saindo do celular e indo para o rosto.",
  [("<p>A Meta lançou a <b>terceira geração</b> dos óculos inteligentes Ray-Ban Meta.</p>"
    "<p>Mais bateria, design mais fino e um preço maior.</p>",
    [stat("US$ 449", "A partir de", "nos EUA", size=100),
     stat("9h", "Bateria", "uma hora a mais que a Gen 2", black=False, color="blue", size=150)]),
   ("<p>O que se mantém: câmera de <b>12 MP</b> e vídeo em <b>3K</b>.</p><p>O que muda: estrutura mais fina e bateria de até <b>9 horas</b>.</p>",
    [lista("Especificações", ["Câmera de 12 MP", "Vídeo em 3K", "Bateria de até 9 horas", "Design mais fino"])]),
   ("<p>Três modelos: <b>Aviator</b>, <b>Wayfarer</b> e o novo <b>Zena</b>, no formato gatinho.</p>",
    [lista("Modelos", ["Aviator", "Wayfarer", "Zena (novo)"], icon="•", cor="#333", black=True, fs=34)]),
   ("<p>O preço subiu: a Gen 3 começa em <b>US$ 449</b>, <b>US$ 70 a mais</b> que a geração anterior.</p>",
    [barras("Preço inicial nos EUA", [("Gen 2", 379, "US$ 379"), ("Gen 3", 449, "US$ 449")])]),
   ("<p>O anúncio foi feito no <b>Meta Connect 2026</b>, e os óculos já estão à venda nos EUA.</p>",
    [aviso("Meta Connect 2026", "óculos à venda desde 23/09", "🕶", black=False, cor=AZUL)]),
   ], fonte="Engadget, 9to5Google e Android Authority (23/09/2026)")

P("oracle-ia-e-empregos", "news",
  "A Oracle cortou 21 mil vagas e citou a IA no documento oficial.",
  "Enquanto reduzia 13% da equipe, a empresa aumentou os investimentos em 162%, para US$ 55,7 bilhões, com foco em data centers de IA.",
  "#oracle #inteligenciaartificial #mercadodetrabalho #tecnologia #negocios",
  "Aprender a usar a IA deixou de ser opcional.",
  [("<p>A Oracle cortou <b>21 mil vagas</b> em um ano.</p><p>E, no documento oficial, citou a <b>inteligência artificial</b> como um dos motivos.</p>",
    [stat("21 mil", "Vagas cortadas", "cerca de 13% da equipe", size=120),
     texto("Documento enviado à SEC", '"A adoção de IA <span class=coral>resultou</span> e pode continuar resultando em <span class=coral>reduções</span> da nossa força de trabalho."', black=True, fs=28)]),
   ("<p>Com o corte, a empresa ficou com <b>141 mil funcionários</b> em tempo integral, em maio de 2026.</p>",
    [stat("141 mil", "Funcionários", "em maio de 2026", black=False, color="blue", size=130)]),
   ("<p>Ao mesmo tempo, a Oracle aumentou os investimentos em <b>162%</b>: de US$ 21,2 bilhões para <b>US$ 55,7 bilhões</b> no ano fiscal.</p>",
    [barras("Investimento (capex)", [("Ano fiscal 2025", 21.2, "US$ 21,2 bi"), ("Ano fiscal 2026", 55.7, "US$ 55,7 bi")])]),
   ("<p>Boa parte vai para data centers. A Oracle tem um contrato de <b>US$ 300 bilhões em 5 anos</b> para fornecer capacidade à OpenAI.</p>",
    [stat("US$ 300 bi", "Contrato", "com a OpenAI, em 5 anos", size=80)]),
   ("<p>A leitura: a IA não muda só tarefas. Ela muda <b>onde as empresas colocam o dinheiro</b>.</p>",
    [fluxo("O movimento", ["Menos vagas", "Mais data centers", "Mais IA"], destaque=True)]),
   ], fonte="CNBC e Forbes (23/06/2026)")

# =============================================================== SITES E NEGÓCIOS

P("7-elementos-de-um-site-que-vende", "site",
  "Site bonito não é o mesmo que site que vende. Estes são os 7 elementos de um site de alta conversão.",
  "Promessa clara no topo, botão de ação, serviços objetivos, prova social, respostas para as dúvidas, contato em um toque e um site rápido no celular.",
  "#criacaodesites #sitesprofissionais #marketingdigital #empreendedorismo #negocios",
  "Faltou algum desses no seu site?",
  [("<p>Site bonito não é o mesmo que <b>site que vende</b>.</p><p>Estes são os <b>7 elementos</b> de um site de alta conversão.</p>",
    [browser("seunegocio.com.br", '<div style="font-size:30px;font-weight:800;line-height:1.2">O que você faz,<br>para <span class=blue>quem</span></div>'
             '<div class=bar style="width:90%"></div><div class=bar style="width:65%"></div>'
             '<div style="display:inline-block;margin-top:22px;background:#4f5dff;border-radius:12px;padding:12px 20px;font-size:19px;font-weight:700">Falar com a empresa</div>'),
     stat("7", "Elementos", "que todo site precisa ter", size=200)]),
   ("<p><b>1.</b> Uma promessa clara no topo: o que você faz e para quem, em uma frase.</p><p><b>2.</b> Um botão de ação visível logo de cara.</p>",
    [lista("Topo da página", ["O que você faz", "Para quem", "Botão de contato"])]),
   ("<p><b>3.</b> Serviços explicados sem enrolação.</p><p><b>4.</b> Prova social: depoimentos, clientes e trabalhos reais.</p>",
    [lista("Meio da página", ["Serviços em tópicos", "Depoimentos", "Portfólio"])]),
   ("<p><b>5.</b> Respostas para as dúvidas mais comuns.</p><p><b>6.</b> Contato em um toque, com WhatsApp e formulário.</p>",
    [lista("Antes do fim", ["Perguntas frequentes", "Botão de WhatsApp", "Formulário curto"])]),
   ("<p><b>7.</b> Velocidade e celular em primeiro lugar.</p><p>Muita gente vai abrir o seu site pelo telefone, então ele precisa ser pensado para a tela pequena.</p>",
    [stat("📱", "Celular primeiro", "pensado para a tela pequena", black=False, color="blue", size=150)]),
   ])

P("instagram-ou-site", "site",
  "Instagram ou site? Essa é a pergunta errada.",
  "O Instagram atrai atenção. O site organiza a informação, aparece no Google e leva o cliente até o contato. Juntos, um alimenta o outro.",
  "#instagramparanegocios #criacaodesites #marketingdigital #empreendedorismo #negocios",
  "Não é escolher um. É fazer os dois trabalharem juntos.",
  [("<p>Instagram <b>ou</b> site? A pergunta está errada.</p><p>Os dois têm funções diferentes, e o seu negócio precisa de ambos.</p>",
    [stat("IG", "Instagram", "atrai atenção", black=False, color="blue", size=160),
     stat("WWW", "Site", "converte e passa confiança", size=110)]),
   ("<p>O Instagram é a <b>vitrine</b>: gera alcance, mostra bastidores e aproxima você do público.</p>",
    [lista("Instagram é bom para", ["Alcance", "Relacionamento", "Bastidores"])]),
   ("<p>O site é o <b>endereço</b>: organiza a informação, aparece no Google e leva o cliente até o contato.</p>",
    [lista("Site é bom para", ["Aparecer no Google", "Explicar os serviços", "Levar ao contato"])]),
   ("<p>No Instagram, a informação se perde no feed. No site, está tudo <b>em um lugar só</b>, organizado do jeito que você quer.</p>",
    [cinza("Só Instagram", ["Preço no direct", "Informação espalhada", "Regras da plataforma"]),
     lista("Com site", ["Tudo em um lugar", "Do seu jeito", "Endereço próprio"])]),
   ("<p>O caminho ideal: o conteúdo atrai no Instagram, o link na bio leva ao site, e o site transforma a visita em <b>contato</b>.</p>",
    [fluxo("O caminho", ["Conteúdo no Instagram", "Link na bio", "Site", "Contato"])]),
   ])

P("5-erros-que-afastam-clientes-do-site", "site",
  "5 erros que fazem o cliente sair do seu site em segundos.",
  "Mensagem confusa, contato escondido, site lento no celular, texto demais e nenhuma prova de confiança. Todos têm solução.",
  "#criacaodesites #experienciadousuario #marketingdigital #empreendedorismo #negocios",
  "Quantos desses erros o seu site tem hoje?",
  [("<p>O cliente entrou no seu site e saiu em segundos?</p><p>Estes são <b>5 erros</b> que afastam visitantes.</p>",
    [aviso("Visitante saiu", "antes de chegar ao contato", X, cor="#ff8a7a"),
     stat("5", "Erros", "que dá para corrigir", black=False, color="blue", size=200)]),
   ("<p><b>1.</b> Não dá para entender o que você faz em poucos segundos.</p><p><b>2.</b> Não existe um botão claro de contato.</p>",
    [nao("Erros 1 e 2", ["Mensagem confusa no topo", "Contato escondido"])]),
   ("<p><b>3.</b> O site é lento ou quebra no celular.</p><p><b>4.</b> Textos longos demais, sem títulos nem tópicos.</p>",
    [nao("Erros 3 e 4", ["Lento ou quebrado no celular", "Blocos de texto sem respiro"])]),
   ("<p><b>5.</b> Nenhuma prova de que você é confiável: sem depoimentos, sem portfólio, sem rosto por trás da marca.</p>",
    [nao("Erro 5", ["Sem depoimentos", "Sem portfólio", "Sem rosto"])]),
   ("<p>Como corrigir:</p>",
    [lista("Correção", ["Frase clara no topo", "Botão visível", "Site leve", "Texto em tópicos", "Prova social"], fs=28)]),
   ])

P("o-que-e-landing-page", "site",
  "Landing page: a página certa quando você quer que o visitante faça uma coisa só.",
  "Um objetivo, uma oferta, um botão. Ideal para anúncios, lançamentos, eventos e promoções.",
  "#landingpage #criacaodesites #trafegopago #marketingdigital #empreendedorismo",
  "Anúncio sem landing page é tráfego sem direção.",
  [("<p>Você sabe o que é uma <b>landing page</b>?</p><p>É a página certa quando você quer que o visitante faça <b>uma coisa só</b>.</p>",
    [browser("suaoferta.com.br", '<div style="font-size:30px;font-weight:800;line-height:1.2">Uma oferta.<br><span class=coral>Um botão.</span></div>'
             '<div class=bar style="width:85%"></div><div class=bar style="width:60%"></div>'
             '<div style="display:inline-block;margin-top:22px;background:#4f5dff;border-radius:12px;padding:12px 20px;font-size:19px;font-weight:700">Quero agendar</div>'),
     stat("1", "Objetivo", "por página", size=200)]),
   ("<p>Landing page é uma página com <b>um único objetivo</b>: agendar, comprar, baixar um material ou chamar no WhatsApp.</p>",
    [lista("Objetivos comuns", ["Agendar uma consulta", "Comprar um produto", "Baixar um material", "Chamar no WhatsApp"])]),
   ("<p>A diferença: o site <b>apresenta a empresa inteira</b>. A landing page <b>foca em uma oferta</b> e tira as distrações.</p>",
    [texto("Site", "Vários serviços, várias páginas, apresenta a empresa.", black=True, fs=30),
     texto("Landing page", 'Uma oferta, uma página, <span class=coral>um botão</span>.', fs=30)]),
   ("<p>Quando usar: em <b>anúncios</b>, lançamentos, eventos, promoções ou para testar uma oferta nova.</p>",
    [lista("Quando usar", ["Anúncios pagos", "Lançamentos", "Eventos", "Promoções"], icon="→")]),
   ("<p>O que não pode faltar: título forte, benefícios em tópicos, prova social e <b>um botão repetido</b> ao longo da página.</p>",
    [fluxo("Estrutura", ["Título forte", "Benefícios", "Prova social", "Botão de ação"])]),
   ])

P("site-lento-custa-clientes", "site",
  "Site lento custa clientes. Veja como testar e melhorar a velocidade do seu.",
  "Imagens pesadas, plugins demais e hospedagem fraca deixam o site lento. O PageSpeed Insights, do Google, mostra onde melhorar.",
  "#criacaodesites #velocidadedosite #seo #marketingdigital #empreendedorismo",
  "Teste o seu site hoje no PageSpeed Insights.",
  [("<p>Site lento <b>custa clientes</b>.</p><p>Ninguém gosta de esperar uma página carregar quando o concorrente está a um toque de distância.</p>",
    [aviso("Carregando...", "e o cliente volta para a busca", "⏳", cor=CORAL),
     stat("⚡", "Velocidade", "faz parte da experiência", black=False, color="blue", size=150)]),
   ("<p>O que deixa um site lento: <b>imagens pesadas</b>, excesso de plugins, hospedagem fraca e código desnecessário.</p>",
    [atencao("Vilões da velocidade", ["Imagens pesadas", "Plugins demais", "Hospedagem fraca", "Código desnecessário"])]),
   ("<p>Como testar: o <b>PageSpeed Insights</b>, ferramenta gratuita do Google, mede o desempenho do site no celular e no computador.</p>",
    [pilula("Teste grátis", "pagespeed.web.dev", "Cole o endereço do seu site")]),
   ("<p>Como melhorar: imagens em formatos modernos, como <b>WebP</b>, só o necessário instalado e uma boa hospedagem.</p>",
    [lista("Melhorias", ["Imagens em WebP", "Menos plugins", "Boa hospedagem", "Cache ativado"])]),
   ("<p>A velocidade também pesa no Google: a <b>experiência na página</b> entra na conta de como os resultados são organizados.</p>",
    [texto("Google", 'Experiência na página, incluindo velocidade, entra na conta do <span class=coral>ranqueamento</span>.', fs=34)]),
   ])

P("dominio-proprio", "site",
  "Domínio próprio: o endereço do seu negócio na internet.",
  "É ele que o cliente digita e lembra, e ainda libera um e-mail profissional. No Brasil, domínios .br são registrados no Registro.br.",
  "#dominio #criacaodesites #registrobr #empreendedorismo #negocios",
  "Registre o nome da sua marca antes que outra pessoa registre.",
  [("<p>Seu negócio ainda não tem um <b>domínio próprio</b>?</p><p>Esse endereço é a base da sua presença digital.</p>",
    [pilula("Domínio", "suaempresa.com.br", "O seu endereço na internet"),
     stat(".br", "Brasil", "registrado no Registro.br", size=170)]),
   ("<p>Domínio é o nome do seu site, como <b>suaempresa.com.br</b>. É ele que o cliente digita, lembra e vê no seu e-mail.</p>",
    [lista("Onde o domínio aparece", ["Endereço do site", "E-mail profissional", "Cartão e redes sociais"])]),
   ("<p>No Brasil, domínios <b>.br</b> são registrados no <b>Registro.br</b>, e o registro precisa ser renovado periodicamente.</p>",
    [texto("Registro.br", 'Responsável pelos domínios <span class=coral>.br</span> no Brasil.', fs=40)]),
   ("<p>Com domínio próprio, você ganha <b>e-mail profissional</b>: contato@suaempresa.com.br passa mais confiança do que um e-mail genérico.</p>",
    [texto("E-mail genérico", "suaempresa2024@...", black=True, fs=30),
     texto("E-mail profissional", 'contato@<span class=coral>suaempresa.com.br</span>', fs=28)]),
   ("<p>Dicas para escolher: nome <b>curto</b>, fácil de falar, sem hífen e sem números.</p>",
    [lista("Boas práticas", ["Curto", "Fácil de falar", "Sem hífen", "Sem números"])]),
   ])

P("botao-de-whatsapp-no-site", "site",
  "O botão de WhatsApp no site pode ser o caminho mais curto até a venda. Veja como fazer do jeito certo.",
  "Botão flutuante, links nos pontos de decisão e uma mensagem pronta que já diz de onde o cliente veio.",
  "#whatsappbusiness #criacaodesites #vendas #empreendedorismo #negocios",
  "Cliente que chama no WhatsApp espera resposta rápida.",
  [("<p>O botão de <b>WhatsApp</b> no site pode ser o caminho mais curto até a venda.</p><p>Desde que esteja bem feito.</p>",
    [pilula("Botão flutuante", "💬 Fale no WhatsApp", "Sempre visível no canto da tela"),
     stat("1", "Toque", "até a conversa", size=200)]),
   ("<p>Onde colocar: um botão <b>flutuante</b> no canto da tela e botões nos pontos de decisão, como depois dos serviços e dos preços.</p>",
    [lista("Onde colocar", ["Flutuante no canto", "Depois dos serviços", "Depois dos preços", "No fim da página"])]),
   ("<p>O segredo é a <b>mensagem pronta</b>: o link do WhatsApp pode abrir a conversa com um texto já preenchido.</p>",
    [pilula("Link com mensagem", "wa.me/55DDDNUMERO?text=Olá", "A conversa já começa com contexto")]),
   ("<p>Exemplo: \"Olá! Vim pelo site e quero um orçamento.\" Assim você já sabe <b>de onde o cliente veio</b> e o que ele quer.</p>",
    [texto("Mensagem pronta", '"Olá! Vim pelo site e quero <span class=coral>um orçamento</span>."', black=True, fs=40)]),
   ("<p>E não adianta ter o botão se ninguém responde. Use o <b>WhatsApp Business</b> com mensagem de saudação e de ausência.</p>",
    [lista("WhatsApp Business", ["Mensagem de saudação", "Mensagem de ausência", "Respostas rápidas", "Catálogo"])]),
   ])

P("checklist-antes-de-publicar-um-site", "site",
  "Checklist: 10 pontos para conferir antes de colocar um site no ar.",
  "Textos, contatos, links, celular, imagens, botões, HTTPS, formulário, Search Console e política de privacidade.",
  "#criacaodesites #checklist #webdesign #empreendedorismo #negocios",
  "Salve este checklist para o seu próximo site.",
  [("<p>Antes de colocar um site no ar, passe por este <b>checklist</b>.</p><p>São 10 pontos que evitam dor de cabeça depois.</p>",
    [stat("10", "Pontos", "para checar antes de publicar", size=200),
     aviso("Publicar", "só depois do checklist", "✓", black=False, cor=AZUL)]),
   ("<p><b>Conteúdo</b> (pontos 1 a 3):</p>",
    [lista("Conteúdo", ["Textos revisados", "Telefone e e-mail corretos", "Links funcionando"])]),
   ("<p><b>Visual</b> (pontos 4 a 6):</p>",
    [lista("Visual", ["Teste no celular", "Imagens leves", "Botões visíveis"])]),
   ("<p><b>Técnico</b> (pontos 7 a 9):</p>",
    [lista("Técnico", ["Cadeado de segurança (HTTPS)", "Formulário testado", "Cadastro no Search Console"])]),
   ("<p>E o décimo: <b>política de privacidade</b>. Se o site coleta dados, a LGPD exige transparência sobre como eles são usados.</p>",
    [texto("Ponto 10", 'Política de privacidade e aviso de <span class=coral>cookies</span>, quando houver coleta de dados.', fs=34)]),
   ])

P("como-o-google-encontra-seu-site", "site",
  "Seu site não aparece no Google? Veja como o Google encontra uma página.",
  "Rastrear, indexar e classificar. O Search Console acelera o processo e o Perfil da Empresa no Google coloca você no Maps.",
  "#seo #google #criacaodesites #marketingdigital #negocios",
  "Site que ninguém encontra não trabalha por você.",
  [("<p>Seu site existe, mas <b>não aparece no Google</b>?</p><p>Veja como o Google encontra e mostra uma página.</p>",
    [fluxo("O caminho", ["Rastrear", "Indexar", "Mostrar nos resultados"])]),
   ("<p><b>1. Rastrear:</b> robôs do Google visitam as páginas seguindo links.</p><p><b>2. Indexar:</b> o conteúdo é analisado e guardado.</p>",
    [lista("Etapas", ["Rastreamento", "Indexação", "Classificação"], icon="→")]),
   ("<p><b>3. Classificar:</b> quando alguém pesquisa, o Google escolhe as páginas mais <b>relevantes</b> para aquela busca.</p>",
    [texto("Relevância", 'Responda <span class=coral>exatamente</span> o que o seu cliente pesquisa.', fs=40)]),
   ("<p>Para acelerar: cadastre o site no <b>Google Search Console</b> e envie o mapa do site (sitemap).</p>",
    [lista("Search Console", ["Verificar o site", "Enviar o sitemap", "Acompanhar erros"])]),
   ("<p>Para negócio local, crie também o <b>Perfil da Empresa no Google</b>: ele aparece no Maps e na busca da sua região.</p>",
    [aviso("Perfil da Empresa", "Google Maps e busca local", "📍", black=False, cor=AZUL)]),
   ])

P("pagina-sobre-que-gera-confianca", "site",
  "A página Sobre do seu site não é sobre você.",
  "É sobre por que o cliente deveria confiar em você: o problema que você resolve, sua história em poucas linhas, provas reais e um convite para o contato.",
  "#criacaodesites #copywriting #marcapessoal #empreendedorismo #negocios",
  "Foto real e texto honesto valem mais do que frase bonita.",
  [("<p>A página <b>Sobre</b> não é sobre você.</p><p>É sobre <b>por que o cliente deveria confiar</b> em você.</p>",
    [texto("Página Sobre", 'Menos biografia. Mais <span class=coral>motivos para confiar</span>.', fs=44)]),
   ("<p>Comece pelo <b>cliente</b>: qual problema você resolve e para quem.</p>",
    [lista("Abertura", ["Problema que resolve", "Para quem", "Como resolve"])]),
   ("<p>Depois, a <b>sua história</b>, curta: como você chegou até aqui e o que te diferencia.</p>",
    [lista("História", ["Origem", "Diferencial", "Valores"], icon="•", cor="#333", black=True)]),
   ("<p>Mostre <b>provas</b>: formação, experiência, trabalhos feitos e fotos reais da equipe e do espaço.</p>",
    [lista("Provas", ["Formação", "Experiência", "Trabalhos feitos", "Fotos reais"])]),
   ("<p>Termine com um <b>convite</b>: um botão para falar com você.</p>",
    [fluxo("Final da página", ["Quem você é", "Por que confiar", "Botão de contato"])]),
   ])

P("prova-social-no-site", "site",
  "O que outros clientes dizem pesa na decisão de quem ainda não te conhece.",
  "Depoimentos com nome, foto e contexto, avaliações do Google e portfólio. E sempre perto do botão de contato.",
  "#provasocial #criacaodesites #vendas #empreendedorismo #negocios",
  "Sempre peça autorização para publicar um depoimento.",
  [("<p>O que outros clientes dizem pesa na decisão de quem <b>ainda não te conhece</b>.</p><p>Isso é prova social.</p>",
    [texto("Exemplo de depoimento", '"Atendimento rápido e <span class=coral>resultado impecável</span>."<div class=sub>Nome, foto e contexto dão peso</div>', black=True, fs=34)]),
   ("<p>Tipos de prova social que funcionam no site:</p>",
    [lista("Tipos", ["Depoimentos", "Avaliações do Google", "Portfólio", "Logos de clientes"])]),
   ("<p>Depoimento bom tem <b>nome, foto e contexto</b>. \"Adorei!\" sozinho não convence.</p>",
    [cinza("Fraco", ["Sem nome", "Sem foto", "Genérico"]),
     lista("Forte", ["Nome real", "Foto", "Situação específica"])]),
   ("<p>Peça do jeito certo: logo depois de entregar, mande uma mensagem com <b>2 ou 3 perguntas</b> simples.</p>",
    [lista("Perguntas", ["Como era antes?", "O que mudou?", "Recomendaria?"], icon="?")]),
   ("<p>Onde colocar: perto dos <b>botões de contato</b>, porque é ali que o cliente decide.</p>",
    [fluxo("Posição", ["Serviço", "Depoimento", "Botão de contato"])]),
   ])

P("nutricionista-precisa-de-site", "site",
  "Nutricionista precisa de site? Se o paciente pesquisa antes de marcar consulta, sim.",
  "O site apresenta a sua abordagem, filtra o paciente e facilita o agendamento, sempre dentro das normas do CFN.",
  "#nutricionista #nutricao #criacaodesites #marketingparanutricionistas #saude",
  "O seu paciente está pesquisando. Ele encontra você?",
  [("<p>Nutricionista precisa de <b>site</b>?</p><p>Se o paciente pesquisa antes de marcar consulta, a resposta é sim.</p>",
    [aviso("Paciente pesquisa", "antes de marcar a consulta", "🔎", black=False, cor=AZUL),
     stat("24h", "Site no ar", "informando enquanto você atende", size=150)]),
   ("<p>O que o site resolve: apresenta a sua <b>abordagem</b>, especialidades e formas de atendimento, presencial e online.</p>",
    [lista("No site", ["Especialidades", "Abordagem", "Presencial e online", "Como agendar"])]),
   ("<p>Ele também <b>filtra</b> o paciente: quem chega pelo site já sabe como você trabalha.</p>",
    [fluxo("Jornada", ["Pesquisa no Google", "Seu site", "Agendamento"])]),
   ("<p>Agendamento facilitado: botão de WhatsApp com mensagem pronta ou link de agenda online.</p>",
    [lista("Agendamento", ["WhatsApp com mensagem pronta", "Agenda online", "Formulário"])]),
   ("<p>Atenção às regras da profissão: a publicidade na nutrição segue as normas do <b>Conselho Federal de Nutricionistas</b>. Nada de prometer resultado.</p>",
    [texto("Ética", 'Comunique com clareza e <span class=coral>sem promessa de resultado</span>.', black=True, fs=38)]),
   ])

P("perguntas-antes-de-contratar-um-site", "site",
  "Vai contratar um site? Faça estas 6 perguntas antes de fechar.",
  "Domínio no seu nome, edição depois da entrega, versão para celular, preparo para o Google, custo anual e suporte.",
  "#criacaodesites #empreendedorismo #negocios #dicas #sitesprofissionais",
  "Salve para usar na sua próxima negociação.",
  [("<p>Vai contratar um site?</p><p>Faça estas <b>6 perguntas</b> antes de fechar.</p>",
    [stat("6", "Perguntas", "antes de fechar", size=200),
     aviso("Contrato", "leia antes de assinar", "✍", black=False, cor=AZUL)]),
   ("<p><b>1.</b> O domínio e a hospedagem ficam no <b>meu nome</b>?</p><p><b>2.</b> Eu consigo editar textos e fotos depois?</p>",
    [lista("Perguntas 1 e 2", ["Domínio no meu nome?", "Consigo editar depois?"], icon="?")]),
   ("<p><b>3.</b> O site é feito para o <b>celular</b>?</p><p><b>4.</b> Ele já vem preparado para o <b>Google</b>?</p>",
    [lista("Perguntas 3 e 4", ["Pensado para celular?", "Preparado para o Google?"], icon="?")]),
   ("<p><b>5.</b> Quanto custa <b>manter</b> por ano?</p><p><b>6.</b> O que está incluído no suporte depois da entrega?</p>",
    [lista("Perguntas 5 e 6", ["Custo anual", "Suporte depois da entrega"], icon="?")]),
   ("<p>Se a resposta da primeira pergunta for não, cuidado: o endereço do seu negócio precisa ser <b>seu</b>.</p>",
    [texto("Regra de ouro", 'Domínio sempre no <span class=coral>seu nome</span>.', black=True, fs=46)]),
   ])

P("site-pensado-para-celular", "site",
  "Seu site foi pensado para o celular ou só funciona no celular?",
  "Texto legível, botões grandes, menu simples e o contato a no máximo 3 toques.",
  "#criacaodesites #mobile #webdesign #empreendedorismo #negocios",
  "Faça o teste dos 3 toques no seu site.",
  [("<p>Seu site foi pensado para o <b>celular</b> ou só \"funciona\" no celular?</p><p>São coisas bem diferentes.</p>",
    [stat("📱", "Celular primeiro", "pensar primeiro na tela pequena", black=False, color="blue", size=150),
     nao("Sinais de problema", ["Texto minúsculo", "Botão difícil de tocar", "Tela cortada"], fs=26)]),
   ("<p><b>Textos legíveis</b> sem precisar dar zoom, e parágrafos curtos.</p>",
    [lista("Leitura", ["Fonte grande", "Parágrafos curtos", "Bom contraste"])]),
   ("<p><b>Botões grandes</b>, fáceis de tocar com o polegar, e espaço entre eles.</p>",
    [lista("Toque", ["Botões grandes", "Espaço entre links", "Ação ao alcance do polegar"])]),
   ("<p><b>Menu simples</b> e a informação mais importante logo no topo.</p>",
    [fluxo("Ordem na tela", ["O que você faz", "Botão de contato", "Detalhes"])]),
   ("<p>Teste agora: abra o seu site no celular e tente <b>entrar em contato</b> em até 3 toques.</p>",
    [texto("Teste dos 3 toques", 'Abrir o site, achar o botão, <span class=coral>falar com você</span>.', black=True, fs=38)]),
   ])

P("lgpd-no-seu-site", "site",
  "Seu site coleta nome, e-mail ou telefone? Então a LGPD vale para ele.",
  "Política de privacidade clara, aviso de cookies quando houver rastreamento e formulário só com o necessário. Conteúdo informativo, não substitui orientação jurídica.",
  "#lgpd #criacaodesites #protecaodedados #empreendedorismo #negocios",
  "Transparência também gera confiança. Conteúdo informativo, não substitui orientação jurídica.",
  [("<p>Seu site coleta nome, e-mail ou telefone?</p><p>Então a <b>LGPD</b> também vale para ele.</p>",
    [stat("LGPD", "Lei 13.709/2018", "Lei Geral de Proteção de Dados", size=130),
     atencao("Coleta de dados", ["Formulários", "Cookies", "Newsletter"])]),
   ("<p>A LGPD, <b>Lei 13.709/2018</b>, define regras para coletar, guardar e usar dados pessoais no Brasil.</p>",
    [texto("Em resumo", 'Transparência sobre <span class=coral>quais dados</span> você coleta e <span class=coral>para quê</span>.', fs=38)]),
   ("<p>O básico no site: uma <b>política de privacidade</b> clara, dizendo quais dados coleta, para que usa e como a pessoa pode pedir a exclusão.</p>",
    [lista("Política de privacidade", ["Quais dados", "Para que usa", "Com quem compartilha", "Como pedir exclusão"])]),
   ("<p>Se o site usa cookies de rastreamento, como os de anúncios e de análise, informe o visitante com um <b>aviso de cookies</b>.</p>",
    [pilula("Aviso de cookies", "Aceitar · Configurar", "Informe antes de rastrear")]),
   ("<p>Colete só o <b>necessário</b>: para um orçamento, nome, telefone e uma mensagem costumam bastar.</p>",
    [lista("Formulário enxuto", ["Nome", "Telefone", "Mensagem"])]),
   ])

P("o-botao-do-seu-site", "site",
  "O botão do seu site diz Enviar? Uma palavra muda o que o cliente entende.",
  "Botão bom diz o que acontece no clique, usa verbo de ação, contrasta com o fundo e aparece nos pontos de decisão.",
  "#copywriting #criacaodesites #conversao #marketingdigital #empreendedorismo",
  "Revise hoje os botões do seu site.",
  [("<p>O botão do seu site diz <b>\"Enviar\"</b>?</p><p>Uma palavra muda o que o cliente entende.</p>",
    [texto("Genérico", "[ Enviar ]", black=True, fs=50),
     texto("Específico", '[ <span class=coral>Quero meu orçamento</span> ]', fs=38)]),
   ("<p>Botão bom diz <b>o que acontece</b> quando a pessoa clica.</p>",
    [lista("Exemplos", ["Quero meu orçamento", "Agendar minha consulta", "Falar com um especialista"], icon="→")]),
   ("<p>Use <b>verbo de ação</b> e escreva como se fosse o cliente falando.</p>",
    [cinza("Evite", ["Enviar", "Clique aqui", "Saiba mais"]),
     lista("Prefira", ["Quero", "Agendar", "Receber"])]),
   ("<p>O botão precisa <b>aparecer</b>: cor que contrasta com o fundo e espaço em volta.</p>",
    [texto("Contraste", 'Se o botão se mistura com o fundo, <span class=coral>ninguém vê</span>.', black=True, fs=40)]),
   ("<p>Repita o botão nos <b>pontos de decisão</b>: no topo, depois dos serviços e no final.</p>",
    [fluxo("Posições", ["Topo", "Depois dos serviços", "Final da página"])]),
   ])

P("ia-consegue-criar-um-site", "site",
  "A IA consegue criar um site. Mas não sabe o que o seu cliente precisa ouvir.",
  "Ela acelera textos, código e layout. A estratégia de conversão continua sendo humana.",
  "#criacaodesites #inteligenciaartificial #webdesign #empreendedorismo #ia",
  "Ferramenta boa, na mão certa, faz diferença.",
  [("<p>A IA consegue criar um site.</p><p>Mas ela não sabe <b>o que o seu cliente precisa ouvir</b>.</p>",
    [texto("IA", 'Gera páginas, textos e código <span class=blue>rápido</span>.', black=True, fs=34),
     texto("Estratégia", 'Sabe <span class=coral>o que o cliente precisa ouvir</span>.', fs=34)]),
   ("<p>Onde a IA ajuda muito: rascunhos de texto, código, ideias de layout e revisão.</p>",
    [lista("A IA ajuda em", ["Rascunhos de texto", "Código", "Ideias de layout", "Revisão"])]),
   ("<p>Onde ela não substitui: entender o <b>seu público</b>, posicionar a sua oferta e saber o que faz alguém entrar em contato.</p>",
    [atencao("Não substitui", ["Conhecer o público", "Posicionar a oferta", "Estratégia de conversão"])]),
   ("<p>Site de alta conversão é <b>estratégia + execução</b>. A IA acelera a execução.</p>",
    [fluxo("A receita", ["Estratégia", "Execução com IA", "Revisão humana"])]),
   ("<p>O risco de fazer sem estratégia: um site bonito que <b>não gera contato</b>.</p>",
    [aviso("Site bonito", "que não gera contato", X, cor="#ff8a7a")]),
   ])

P("whatsapp-business-recursos", "site",
  "WhatsApp Business: 5 recursos para organizar o atendimento do seu negócio.",
  "Perfil comercial, saudação, ausência, respostas rápidas, etiquetas e catálogo.",
  "#whatsappbusiness #atendimento #empreendedorismo #negocios #vendas",
  "WhatsApp organizado é cliente bem atendido.",
  [("<p>Você usa o <b>WhatsApp Business</b> ou o WhatsApp comum no seu negócio?</p><p>Veja o que dá para organizar.</p>",
    [stat("5", "Recursos", "para organizar o atendimento", size=190)]),
   ("<p><b>Perfil comercial:</b> endereço, horário, site e descrição do negócio em um só lugar.</p>",
    [lista("Perfil comercial", ["Endereço", "Horário", "Site", "Descrição"])]),
   ("<p><b>Mensagem de saudação</b> para quem chama pela primeira vez e <b>mensagem de ausência</b> fora do horário.</p>",
    [lista("Mensagens automáticas", ["Saudação", "Ausência"])]),
   ("<p><b>Respostas rápidas</b> para perguntas frequentes e <b>etiquetas</b> para organizar os contatos.</p>",
    [lista("Organização", ["Respostas rápidas", "Etiquetas"])]),
   ("<p><b>Catálogo</b> com produtos e serviços, para o cliente ver tudo sem sair da conversa.</p>",
    [aviso("Catálogo", "produtos e serviços na conversa", "🛍", black=False, cor=AZUL)]),
   ])

# =============================================================== IA NA PRÁTICA

P("o-que-e-agente-de-ia", "ia",
  "Chatbot responde. Agente de IA faz. Entenda a diferença.",
  "O agente recebe um objetivo, planeja e usa ferramentas para executar. Por isso, precisa de limites claros.",
  "#agentesdeia #inteligenciaartificial #tecnologia #produtividade #ia",
  "O futuro do trabalho passa por saber delegar para a IA com segurança.",
  [("<p>Chatbot <b>responde</b>. Agente de IA <b>faz</b>.</p><p>Entenda a diferença que está mudando o jeito de trabalhar.</p>",
    [texto("Chatbot", 'Você pergunta, ele <span class=blue>responde</span>.', black=True, fs=36),
     texto("Agente", 'Você pede, ele <span class=coral>executa</span>.', fs=36)]),
   ("<p>Um agente de IA recebe um <b>objetivo</b>, planeja os passos e usa <b>ferramentas</b> para chegar lá: navegador, e-mail, planilhas e sistemas.</p>",
    [fluxo("Como funciona", ["Objetivo", "Plano", "Ferramentas", "Resultado"])]),
   ("<p>Exemplos: pesquisar concorrentes e montar uma tabela, organizar a caixa de entrada, preencher um formulário, atualizar um CRM.</p>",
    [lista("Exemplos", ["Pesquisa e tabela", "Caixa de entrada", "Formulários", "CRM"])]),
   ("<p>O ponto de atenção: agente tem <b>acesso</b>. Quanto mais ele pode fazer, mais importante é definir limites.</p>",
    [atencao("Defina", ["O que ele pode acessar", "O que precisa de aprovação", "O que é proibido"])]),
   ("<p>Comece pequeno: tarefas repetitivas, de baixo risco e fáceis de conferir.</p>",
    [lista("Bom para começar", ["Tarefas repetitivas", "Baixo risco", "Fácil de conferir"])]),
   ])

P("5-usos-de-ia-no-seu-negocio", "ia",
  "5 formas de usar IA no seu negócio a partir de hoje, sem programar.",
  "Atendimento, conteúdo, propostas, planilhas e reuniões. A IA faz o rascunho, você revisa e decide.",
  "#inteligenciaartificial #produtividade #empreendedorismo #negocios #ia",
  "Qual desses você vai testar primeiro?",
  [("<p><b>5 formas</b> de usar IA no seu negócio a partir de hoje.</p><p>Sem precisar saber programar.</p>",
    [stat("5", "Usos", "para começar hoje", size=200),
     stat("0", "Código", "necessário", black=False, color="blue", size=200)]),
   ("<p><b>1. Atendimento:</b> rascunhar respostas para as perguntas que chegam todo dia.</p><p><b>2. Conteúdo:</b> ideias de posts, roteiros e legendas.</p>",
    [lista("1 e 2", ["Rascunho de respostas", "Ideias e roteiros de conteúdo"])]),
   ("<p><b>3. Propostas:</b> transformar anotações soltas em uma proposta comercial organizada.</p>",
    [copie('"Transforme estas anotações em uma <span class=coral>proposta comercial</span> clara e objetiva: [anotações]."')]),
   ("<p><b>4. Planilhas:</b> criar fórmulas e resumir dados.</p><p><b>5. Reuniões:</b> transformar transcrições em resumos e próximos passos.</p>",
    [lista("4 e 5", ["Fórmulas e resumos", "Atas e próximos passos"])]),
   ("<p>A regra: a IA faz o <b>primeiro rascunho</b>, você revisa e decide. Nunca publique nem envie sem ler.</p>",
    [fluxo("Regra de ouro", ["A IA rascunha", "Você revisa", "Você decide"])]),
   ])

P("como-escrever-um-bom-prompt", "ia",
  "A resposta da IA é tão boa quanto o pedido. Use esta estrutura de 4 partes.",
  "Contexto, tarefa, formato e exemplo. E, se não gostou, peça ajustes.",
  "#prompt #inteligenciaartificial #chatgpt #produtividade #ia",
  "Salve essa estrutura e use no seu próximo pedido.",
  [("<p>A resposta da IA é tão boa quanto o <b>pedido</b> que você faz.</p><p>Use esta estrutura de 4 partes.</p>",
    [stat("4", "Partes", "de um bom prompt", size=200),
     fluxo("Estrutura", ["Contexto", "Tarefa", "Formato", "Exemplo"])]),
   ("<p><b>1. Contexto:</b> quem você é, para quem é o conteúdo e qual o objetivo.</p>",
    [texto("Contexto", '"Sou dono de uma clínica e quero atrair <span class=coral>novos pacientes</span>."', black=True, fs=36)]),
   ("<p><b>2. Tarefa:</b> o que exatamente você quer, com um verbo claro.</p>",
    [texto("Tarefa", '"<span class=coral>Escreva</span> 3 opções de título para uma página de agendamento."', black=True, fs=36)]),
   ("<p><b>3. Formato:</b> tamanho, tom e estrutura da resposta.</p><p><b>4. Exemplo:</b> mostre algo de que você gosta.</p>",
    [lista("Formato e exemplo", ["Tamanho", "Tom de voz", "Tópicos ou tabela", "Um modelo de referência"])]),
   ("<p>E converse: se não gostou, diga <b>o que mudar</b>. Ajustar faz parte do processo.</p>",
    [fluxo("O ciclo", ["Pedido", "Resposta", "Ajuste"])]),
   ])

P("5-prompts-para-empresarios", "ia",
  "5 prompts prontos para empresários. Copie e adapte.",
  "Dúvidas dos clientes, proposta comercial, resposta difícil, ideias de conteúdo e organização de tarefas.",
  "#prompt #chatgpt #inteligenciaartificial #empreendedorismo #produtividade",
  "Troque o que está entre colchetes pelas informações do seu negócio.",
  [("<p><b>5 prompts prontos</b> para empresários.</p><p>Copie, adapte ao seu negócio e use hoje.</p>",
    [stat("5", "Prompts", "prontos para copiar", size=200),
     aviso("Salve", "para usar depois", "🔖", black=False, cor=AZUL)]),
   ("<p><b>Prompt 1:</b> as dúvidas do seu cliente.</p>",
    [copie('"Liste as 10 dúvidas mais comuns de quem contrata <span class=coral>[seu serviço]</span> e responda cada uma em até 2 frases."')]),
   ("<p><b>Prompt 2:</b> proposta comercial.</p>",
    [copie('"Com base nestas anotações, escreva uma proposta comercial com escopo, prazo e investimento: <span class=coral>[anotações]</span>."')]),
   ("<p><b>Prompt 3:</b> resposta difícil.</p>",
    [copie('"Escreva uma resposta educada e firme para este cliente que pediu desconto: <span class=coral>[mensagem]</span>."')]),
   ("<p><b>Prompts 4 e 5:</b> conteúdo e organização.</p>",
    [lista("Copie e adapte", ['"Crie 10 ideias de posts sobre [tema] para [público]."', '"Organize estas tarefas por prioridade e prazo: [lista]."'], icon="→", fs=26)]),
   ])

P("o-que-delegar-para-a-ia", "ia",
  "O que delegar para a IA, e o que nunca deve sair das suas mãos.",
  "Delegue o repetitivo, divida o que exige contexto e mantenha decisões, negociação e dinheiro com você.",
  "#inteligenciaartificial #produtividade #gestao #empreendedorismo #ia",
  "A IA é apoio. A responsabilidade continua sendo sua.",
  [("<p>O que delegar para a IA, e o que <b>nunca</b> deve sair das suas mãos.</p>",
    [lista("Delegue", ["Rascunhos", "Resumos", "Pesquisas"]),
     atencao("Mantenha", ["Decisões", "Relacionamento", "Aprovação final"])]),
   ("<p><b>Delegue</b> o que é repetitivo e fácil de conferir.</p>",
    [lista("Delegue", ["Rascunhos de texto", "Resumos de documentos", "Organização de dados", "Primeiras ideias"])]),
   ("<p><b>Divida</b> o que exige contexto: a IA sugere, você ajusta. Exemplo: propostas e roteiros.</p>",
    [fluxo("Divida", ["A IA sugere", "Você ajusta", "Você aprova"])]),
   ("<p><b>Mantenha</b> com você: decisões importantes, negociação, relacionamento e tudo que envolva dinheiro ou dados sensíveis.</p>",
    [atencao("Mantenha", ["Decisões estratégicas", "Negociação", "Pagamentos", "Dados sensíveis"])]),
   ("<p>A pergunta para decidir: <b>se der errado, qual o tamanho do estrago?</b> Quanto maior, mais controle humano.</p>",
    [texto("Pergunta-chave", 'Se der errado, <span class=coral>qual o tamanho do estrago?</span>', black=True, fs=42)]),
   ])

P("o-que-nao-colar-na-ia", "ia",
  "Cuidado com o que você cola numa IA. Alguns dados nunca deveriam sair da sua empresa.",
  "Senhas, cartões e dados de clientes ficam de fora. Confira as configurações de privacidade e anonimize quando precisar.",
  "#privacidade #inteligenciaartificial #seguranca #lgpd #ia",
  "Na dúvida, não cole.",
  [("<p>Cuidado com o que você <b>cola</b> numa IA.</p><p>Alguns dados nunca deveriam sair da sua empresa.</p>",
    [aviso("Pare antes de colar", "dados sensíveis", "✋", cor=CORAL),
     nao("Nunca cole", ["Senhas", "Dados de clientes", "Contratos sigilosos"], fs=27)]),
   ("<p>Não cole: <b>senhas</b>, chaves de acesso, números de cartão e documentos pessoais.</p>",
    [nao("Acesso", ["Senhas", "Chaves de API", "Cartões", "Documentos"])]),
   ("<p>Evite: dados de <b>clientes</b> que identificam a pessoa, como nome, CPF, telefone e histórico.</p>",
    [nao("Clientes", ["Nome completo", "CPF", "Telefone", "Histórico"])]),
   ("<p>Leia a política da ferramenta: em muitas delas, dá para <b>desativar</b> o uso das suas conversas para treinamento, e os planos empresariais costumam ter regras próprias.</p>",
    [lista("Verifique", ["Configuração de privacidade", "Uso para treinamento", "Plano empresarial"])]),
   ("<p>Quando precisar usar dados reais, <b>anonimize</b>: troque nomes por \"Cliente A\" e remova os números.</p>",
    [texto("Anonimize", '"Maria Souza, CPF..." vira <span class=coral>"Cliente A"</span>.', black=True, fs=40)]),
   ])

P("por-que-a-ia-inventa-coisas", "ia",
  "A IA pode inventar uma informação com toda a confiança. Isso se chama alucinação.",
  "Acontece mais com números, datas, citações e leis. Peça as fontes, abra os links e confira na origem.",
  "#inteligenciaartificial #chatgpt #checagem #tecnologia #ia",
  "A IA acelera o trabalho, mas a checagem continua sendo sua.",
  [("<p>A IA pode <b>inventar</b> uma informação com toda a confiança do mundo.</p><p>Isso tem nome: alucinação.</p>",
    [aviso("Alucinação", "resposta errada com cara de certa", "?", cor=CORAL),
     stat("✓", "Confira", "antes de usar", black=False, color="blue", size=150)]),
   ("<p>Por que acontece: modelos de linguagem geram o texto <b>mais provável</b>, não necessariamente o verdadeiro.</p>",
    [texto("Como funciona", 'A IA prevê a <span class=coral>próxima palavra</span>. Às vezes, a mais provável está errada.', black=True, fs=36)]),
   ("<p>Onde mais aparece: números, datas, citações, leis, nomes de pessoas e links.</p>",
    [atencao("Atenção redobrada", ["Números e datas", "Citações", "Leis e normas", "Links e fontes"])]),
   ("<p>Como se proteger: peça as <b>fontes</b>, abra os links e confira o dado na origem.</p>",
    [fluxo("Checagem", ["Peça a fonte", "Abra o link", "Confira na origem"])]),
   ("<p>E use o pedido a seu favor: \"se não tiver certeza, diga que não sabe\".</p>",
    [texto("Adicione ao prompt", '"Se não tiver certeza, <span class=coral>diga que não sabe</span>."', black=True, fs=40)]),
   ])

P("ia-no-atendimento-do-whatsapp", "ia",
  "IA no atendimento do WhatsApp: ajuda ou atrapalha? Depende da configuração.",
  "Use para o que é previsível, dê uma base oficial de informações, proíba inventar preços e sempre ofereça contato com uma pessoa.",
  "#whatsapp #atendimento #inteligenciaartificial #automacao #negocios",
  "Automação boa é a que o cliente nem percebe.",
  [("<p>IA no atendimento do WhatsApp: <b>ajuda</b> ou <b>atrapalha</b>?</p><p>Depende de como você configura.</p>",
    [lista("Ajuda", ["Responde fora do horário", "Tira dúvidas simples", "Organiza pedidos"], fs=27),
     nao("Atrapalha", ["Respostas erradas", "Cliente preso no robô", "Tom frio"], fs=27)]),
   ("<p>Use IA para o que é <b>previsível</b>: horários, endereço, serviços, preços e status de pedidos.</p>",
    [lista("Previsível", ["Horários", "Endereço", "Serviços e preços", "Status de pedido"])]),
   ("<p>Sempre ofereça um caminho para <b>falar com uma pessoa</b>. Ninguém gosta de ficar preso num robô.</p>",
    [pilula("Opção obrigatória", "Falar com um atendente", "Visível em todas as conversas")]),
   ("<p>Dê à IA uma <b>base de informações</b> oficial e atualizada, e proíba que ela invente preços ou prazos.</p>",
    [atencao("Configure", ["Base de informações", "Proibido inventar preço", "Proibido prometer prazo"])]),
   ("<p>Revise as conversas toda semana para ajustar respostas e descobrir dúvidas novas.</p>",
    [fluxo("Rotina semanal", ["Ler as conversas", "Ajustar respostas", "Atualizar a base"])]),
   ])

P("conteudo-com-ia-sem-parecer-robo", "ia",
  "Como criar conteúdo com IA sem parecer robô.",
  "Parta da sua experiência, ensine o seu tom de voz, corte frases genéricas e leia em voz alta antes de publicar.",
  "#conteudodigital #inteligenciaartificial #marketingdigital #copywriting #ia",
  "A IA acelera. A autenticidade continua sendo sua.",
  [("<p>Dá para criar conteúdo com IA <b>sem parecer robô</b>.</p><p>O segredo está no que você coloca antes.</p>",
    [texto("Robô", '"No mundo atual, é fundamental..."', black=True, fs=34),
     texto("Você", '"Semana passada, um cliente me perguntou..."', fs=34)]),
   ("<p>Comece pela sua <b>experiência</b>: casos reais, opiniões e bastidores. A IA organiza, a história é sua.</p>",
    [fluxo("Processo", ["Sua ideia", "A IA organiza", "Você revisa"])]),
   ("<p>Ensine o seu <b>tom de voz</b>: cole textos antigos seus e peça para a IA seguir o estilo.</p>",
    [copie('"Escreva no mesmo estilo destes textos: <span class=coral>[seus textos]</span>."')]),
   ("<p>Corte os <b>vícios</b> típicos: frases genéricas, exagero de emojis e conclusões óbvias.</p>",
    [nao("Corte", ["Frases genéricas", "Excesso de emojis", "Conclusões óbvias", "Palavras difíceis à toa"])]),
   ("<p>Leia <b>em voz alta</b> antes de publicar. Se você não falaria daquele jeito, reescreva.</p>",
    [texto("Teste final", 'Leia <span class=coral>em voz alta</span>.', black=True, fs=46)]),
   ])

P("o-que-sao-tokens-de-ia", "ia",
  "Tokens: a unidade que explica o custo e o limite das conversas com IA.",
  "Token é um pedaço de texto. As APIs cobram por milhão de tokens, e cada modelo tem uma janela de contexto.",
  "#inteligenciaartificial #tokens #tecnologia #chatgpt #ia",
  "Entender tokens ajuda a usar a IA melhor e a gastar menos.",
  [("<p>Você já ouviu falar em <b>tokens</b> de IA?</p><p>Eles explicam o custo e o limite das conversas.</p>",
    [stat("TOKEN", "A unidade", "que a IA lê e escreve", size=110),
     texto("Ilustração", '"inteli" · "gência"<div class=sub>Uma palavra pode virar mais de um token</div>', black=True, fs=34)]),
   ("<p>Token é um <b>pedaço de texto</b>: pode ser uma palavra inteira, parte dela ou um sinal de pontuação.</p>",
    [lista("Um token pode ser", ["Uma palavra", "Parte de uma palavra", "Pontuação"])]),
   ("<p>Nas APIs de IA, o preço é cobrado <b>por milhão de tokens</b>, separando entrada (o que você envia) e saída (o que a IA responde).</p>",
    [texto("Entrada", "O que você envia", fs=36), texto("Saída", "O que a IA responde", black=True, fs=36)]),
   ("<p>Cada modelo tem uma <b>janela de contexto</b>: o limite de tokens que ele consegue considerar de uma vez.</p>",
    [texto("Janela de contexto", 'Quanto de conversa e documento a IA <span class=coral>consegue ler de uma vez</span>.', fs=36)]),
   ("<p>Na prática: conversas muito longas podem fazer a IA perder detalhes do começo. Para um assunto novo, abra uma <b>nova conversa</b>.</p>",
    [texto("Dica", 'Assunto novo, <span class=coral>conversa nova</span>.', black=True, fs=46)]),
   ])

P("como-escolher-uma-ferramenta-de-ia", "ia",
  "Tem uma ferramenta de IA nova toda semana. Use estes 5 critérios para escolher.",
  "Tarefa real, qualidade no seu trabalho, privacidade, integração e custo. E teste por uma semana.",
  "#inteligenciaartificial #ferramentasdeia #produtividade #tecnologia #ia",
  "Menos ferramentas, bem usadas, valem mais.",
  [("<p>Tem uma ferramenta de IA nova a cada semana.</p><p>Use estes <b>5 critérios</b> para escolher.</p>",
    [stat("5", "Critérios", "para escolher bem", size=200)]),
   ("<p><b>1. Tarefa:</b> ela resolve um problema real do seu dia?</p><p><b>2. Qualidade:</b> teste com um trabalho seu, não com o exemplo pronto.</p>",
    [lista("1 e 2", ["Resolve um problema real?", "Teste com um trabalho seu"])]),
   ("<p><b>3. Privacidade:</b> o que acontece com os seus dados?</p>",
    [atencao("3. Privacidade", ["Uso para treinamento", "Onde os dados ficam", "Plano empresarial"])]),
   ("<p><b>4. Integração:</b> conversa com as ferramentas que você já usa?</p><p><b>5. Custo:</b> o preço cabe no uso real?</p>",
    [lista("4 e 5", ["Integra com o que você usa", "Custo pelo uso real"])]),
   ("<p>Teste por uma semana com uma tarefa específica. Se não economizou tempo, <b>não é a ferramenta certa</b> para você.</p>",
    [texto("Teste de 1 semana", 'Economizou tempo? <span class=coral>Fica.</span> Não economizou? <span class=blue>Sai.</span>', black=True, fs=38)]),
   ])

P("ia-para-planilhas", "ia",
  "Você não precisa decorar fórmulas de planilha. A IA escreve para você.",
  "Descreva as colunas e o resultado, peça a explicação e confira com uma amostra.",
  "#excel #planilhas #inteligenciaartificial #produtividade #ia",
  "Salve para usar na próxima planilha.",
  [("<p>Você não precisa decorar <b>fórmulas</b> de planilha.</p><p>A IA escreve para você.</p>",
    [texto("Pedido", '"Crie uma fórmula que some as vendas de março da coluna C."', black=True, fs=32),
     texto("Resposta", '<span class=coral>=SOMASES(...)</span>', fs=42)]),
   ("<p>Descreva o que você quer em português, dizendo as <b>colunas</b> e o resultado esperado.</p>",
    [lista("Informe", ["Nome das colunas", "Onde estão os dados", "Resultado esperado"])]),
   ("<p>Peça também a <b>explicação</b>: entender a fórmula ajuda a corrigir depois.</p>",
    [copie('"Explique <span class=coral>passo a passo</span> o que essa fórmula faz."')]),
   ("<p>Outros usos: limpar dados, montar tabelas dinâmicas, sugerir gráficos e resumir resultados.</p>",
    [lista("Outros usos", ["Limpar dados", "Tabela dinâmica", "Sugerir gráficos", "Resumir resultados"])]),
   ("<p>Sempre confira com uma <b>amostra</b>: calcule uma linha na mão e compare.</p>",
    [texto("Checagem", 'Calcule uma linha <span class=coral>na mão</span> e compare.', black=True, fs=42)]),
   ])

P("3-prompts-para-revisar-textos", "ia",
  "Use a IA como revisora, não só como escritora.",
  "3 prompts para deixar qualquer texto mais claro, encontrar pontos fracos e ver pela ótica do cliente.",
  "#prompt #copywriting #inteligenciaartificial #produtividade #ia",
  "Salve para revisar o seu próximo texto.",
  [("<p>Use a IA como <b>revisora</b>, não só como escritora.</p><p>3 prompts para melhorar qualquer texto.</p>",
    [stat("3", "Prompts", "de revisão", size=200)]),
   ("<p><b>Prompt 1:</b> clareza.</p>",
    [copie('"Reescreva este texto com frases mais curtas e diretas, sem mudar o sentido: <span class=coral>[texto]</span>."')]),
   ("<p><b>Prompt 2:</b> crítica.</p>",
    [copie('"Aponte 3 pontos fracos deste texto e explique por quê: <span class=coral>[texto]</span>."')]),
   ("<p><b>Prompt 3:</b> o olhar do cliente.</p>",
    [copie('"Como um cliente de <span class=coral>[perfil]</span> reagiria a este texto? O que ele não entenderia?"')]),
   ("<p>Aceite as sugestões com critério: a IA <b>sugere</b>, você decide o que faz sentido para a sua marca.</p>",
    [fluxo("Processo", ["Seu texto", "Crítica da IA", "Sua decisão"])]),
   ])

P("ia-para-reunioes", "ia",
  "Reunião boa termina com próximos passos. A IA ajuda nisso.",
  "Transcreva com autorização, peça decisões, responsáveis e prazos, e envie o resumo no mesmo dia.",
  "#reunioes #produtividade #inteligenciaartificial #gestao #ia",
  "Menos tempo escrevendo ata, mais tempo executando.",
  [("<p>Reunião boa termina com <b>próximos passos</b>, não só com conversa.</p><p>A IA ajuda nisso.</p>",
    [fluxo("Da reunião à ação", ["Transcrição", "Resumo", "Próximos passos"])]),
   ("<p>Grave ou transcreva a reunião <b>com a autorização</b> de todos os participantes.</p>",
    [aviso("Antes de gravar", "peça autorização a todos", "🎙", black=False, cor=AZUL)]),
   ("<p>Peça à IA um resumo com <b>decisões, responsáveis e prazos</b>.</p>",
    [copie('"Resuma esta reunião em decisões, <span class=coral>responsável</span> e <span class=coral>prazo</span> de cada tarefa."')]),
   ("<p>Mande o resumo para todos no mesmo dia. Assim ninguém sai com uma versão diferente do combinado.</p>",
    [lista("O resumo tem", ["Decisões", "Tarefas", "Responsáveis", "Prazos"])]),
   ("<p>Cuidado com reuniões sigilosas: confira onde a ferramenta guarda as gravações e quem tem acesso.</p>",
    [atencao("Atenção", ["Onde fica a gravação", "Quem tem acesso", "Por quanto tempo"])]),
   ])

# =============================================================== TECNOLOGIA E SEGURANÇA

P("o-que-e-mcp", "tech",
  "Você vai ouvir muito falar em MCP. Entenda em 1 minuto.",
  "É o padrão aberto que conecta agentes de IA a aplicativos. Um conector, várias IAs. E cada conexão é um acesso.",
  "#mcp #agentesdeia #inteligenciaartificial #tecnologia #ia",
  "Entender MCP é entender como os agentes de IA vão trabalhar.",
  [("<p>Você vai ouvir muito falar em <b>MCP</b>.</p><p>É o padrão que conecta agentes de IA aos seus aplicativos.</p>",
    [stat("MCP", "Model Context Protocol", "", size=150),
     fluxo("Conexão", ["Agente de IA", "MCP", "Seus apps"])]),
   ("<p>O MCP, <b>Model Context Protocol</b>, é um padrão aberto apresentado pela Anthropic no fim de 2024.</p>",
    [texto("Origem", 'Padrão <span class=coral>aberto</span>, apresentado pela Anthropic em novembro de 2024.', fs=36)]),
   ("<p>A ideia: em vez de criar uma integração diferente para cada IA, o serviço cria <b>um conector</b> e várias IAs usam.</p>",
    [cinza("Sem padrão", ["Uma integração por IA", "Mais trabalho", "Mais custo"]),
     lista("Com MCP", ["Um conector", "Várias IAs", "Menos retrabalho"])]),
   ("<p>Exemplos de uso: agentes que acessam e-mail, agenda, arquivos, sistemas da empresa e até a casa inteligente.</p>",
    [lista("Exemplos", ["E-mail e agenda", "Arquivos", "Sistemas internos", "Casa inteligente"])]),
   ("<p>Atenção: conectar é dar <b>acesso</b>. Autorize só o que for necessário.</p>",
    [texto("Regra", 'Cada conexão é uma <span class=coral>porta aberta</span>. Abra só as necessárias.', black=True, fs=38)]),
   ])

P("o-que-e-npu", "tech",
  "Notebooks e celulares novos vêm com NPU. Entenda o que é.",
  "É o chip especializado em IA. Roda recursos como legenda ao vivo e edição de fotos no próprio aparelho, gastando menos energia.",
  "#npu #tecnologia #inteligenciaartificial #notebook #hardware",
  "Na próxima compra, olhe também a NPU.",
  [("<p>Notebooks e celulares novos agora vêm com <b>NPU</b>.</p><p>Entenda o que é e para que serve.</p>",
    [stat("NPU", "Neural Processing Unit", "", size=150),
     lista("No chip", ["CPU", "GPU", "NPU"], icon="•", cor="#333", black=True, fs=34)]),
   ("<p>NPU é um processador feito para tarefas de <b>inteligência artificial</b>, como reconhecer voz e imagem.</p>",
    [texto("NPU", 'Chip especializado em <span class=coral>tarefas de IA</span>.', fs=42)]),
   ("<p>A divisão: a <b>CPU</b> cuida do geral, a <b>GPU</b> dos gráficos e a <b>NPU</b> da IA, gastando menos energia.</p>",
    [lista("Quem faz o quê", ["CPU: tarefas gerais", "GPU: gráficos", "NPU: IA com menos energia"])]),
   ("<p>Na prática: legenda ao vivo, desfoque de fundo em chamadas e edição de fotos com IA rodando <b>no próprio aparelho</b>.</p>",
    [lista("Exemplos", ["Legenda ao vivo", "Fundo desfocado", "Edição de fotos", "Tradução"])]),
   ("<p>Vantagem extra: quando a IA roda no aparelho, parte dos dados <b>não precisa ir para a nuvem</b>.</p>",
    [texto("Privacidade", 'Processar no aparelho reduz o envio de dados <span class=coral>para a nuvem</span>.', black=True, fs=36)]),
   ])

P("o-que-e-api", "tech",
  "API explicada para quem não é programador: pense num garçom.",
  "A API leva o pedido de um sistema e traz a resposta de outro. É assim que o site calcula frete, faz login com Google e usa IA.",
  "#api #tecnologia #programacao #inteligenciaartificial #negocios",
  "Quando alguém disser \"integra por API\", você já sabe o que é.",
  [("<p><b>API</b> explicada para quem não é programador.</p><p>Pense num garçom.</p>",
    [fluxo("O garçom", ["Você (cliente)", "API (garçom)", "Cozinha (sistema)"])]),
   ("<p>Você não entra na cozinha: faz o pedido ao garçom, e ele leva e traz o prato. A API faz isso entre <b>sistemas</b>.</p>",
    [texto("API", 'Leva o <span class=coral>pedido</span> de um sistema e traz a <span class=blue>resposta</span> de outro.', fs=38)]),
   ("<p>Exemplos do dia a dia: o site que calcula o frete, o login com Google e o pagamento na loja online.</p>",
    [lista("Exemplos", ["Cálculo de frete", "Login com Google", "Pagamento online", "Mapa no site"])]),
   ("<p>Na IA: quando um app usa um modelo de IA por trás, geralmente ele conversa com esse modelo por <b>API</b>.</p>",
    [fluxo("Na IA", ["Seu app", "API do modelo", "Resposta"])]),
   ("<p>No seu negócio: APIs permitem <b>conectar</b> site, WhatsApp, sistema de vendas e agenda.</p>",
    [lista("Conexões", ["Site", "WhatsApp", "Vendas", "Agenda"])]),
   ])

P("onde-fica-a-nuvem", "tech",
  "Seus arquivos estão na nuvem. Mas onde fica a nuvem?",
  "São data centers de outras empresas. Traz acesso de qualquer lugar, mas exige senha forte, verificação em duas etapas e um backup de verdade.",
  "#nuvem #tecnologia #seguranca #backup #produtividade",
  "Entender a nuvem ajuda a proteger o que é seu.",
  [("<p>Seus arquivos estão \"na nuvem\".</p><p>Mas <b>onde fica</b> a nuvem?</p>",
    [aviso("A nuvem", "é o computador de outra empresa", "☁", black=False, cor=AZUL),
     stat("24h", "Acesso", "de qualquer lugar", size=150)]),
   ("<p>A nuvem são <b>data centers</b>: prédios cheios de servidores, de empresas como Amazon, Google e Microsoft.</p>",
    [texto("Na prática", 'Servidores em <span class=coral>data centers</span>, acessados pela internet.', fs=38)]),
   ("<p>Vantagens: acesso de qualquer lugar, cópia automática e não precisar manter servidor próprio.</p>",
    [lista("Vantagens", ["Acesso de qualquer lugar", "Cópia automática", "Sem servidor próprio"])]),
   ("<p>Cuidados: senha forte, <b>verificação em duas etapas</b> e atenção a quem tem acesso aos arquivos compartilhados.</p>",
    [atencao("Cuidados", ["Senha forte", "Verificação em duas etapas", "Revisar compartilhamentos"])]),
   ("<p>Nuvem não é backup completo: se você apaga um arquivo sincronizado, ele pode sumir <b>em todos os aparelhos</b>.</p>",
    [texto("Atenção", 'Sincronizar <span class=coral>não é</span> o mesmo que fazer backup.', black=True, fs=40)]),
   ])

P("verificacao-em-duas-etapas", "tech",
  "Se a sua senha vazar, o que protege a sua conta? A verificação em duas etapas.",
  "Um segundo fator além da senha. Prefira app autenticador ou chave de segurança e comece pelo e-mail e pelo WhatsApp.",
  "#seguranca #verificacaoemduasetapas #whatsapp #tecnologia #golpe",
  "Ative hoje. Leva menos de um minuto.",
  [("<p>Se a sua senha vazar, o que protege a sua conta?</p><p>A <b>verificação em duas etapas</b>.</p>",
    [fluxo("Login seguro", ["Senha", "Código ou chave", "Acesso"]),
     stat("2", "Etapas", "senha + segundo fator", size=200)]),
   ("<p>Como funciona: além da senha, você confirma com um <b>segundo fator</b>, como um código no celular.</p>",
    [lista("Segundo fator", ["App autenticador", "Chave de segurança", "Código por SMS"])]),
   ("<p>Chave de segurança e app autenticador são <b>mais seguros</b> que o código por SMS.</p>",
    [lista("Do mais ao menos seguro", ["Chave de segurança", "App autenticador", "SMS"], icon="→")]),
   ("<p>Ative primeiro onde dói mais: <b>e-mail</b>, WhatsApp, Instagram, banco e as contas da empresa.</p>",
    [atencao("Prioridade", ["E-mail", "WhatsApp", "Instagram", "Banco"])]),
   ("<p>No WhatsApp: Configurações → Conta → <b>Confirmação em duas etapas</b>.</p>",
    [pilula("WhatsApp", "Configurações → Conta", "Confirmação em duas etapas")]),
   ])

P("regra-3-2-1-de-backup", "tech",
  "A regra 3-2-1 de backup que toda empresa deveria seguir.",
  "3 cópias, 2 tipos de armazenamento e 1 cópia fora do local. E teste se o backup realmente restaura.",
  "#backup #seguranca #tecnologia #empreendedorismo #dados",
  "Quando foi a última vez que você testou o seu backup?",
  [("<p>Computador quebra, celular é roubado, arquivo é apagado.</p><p>Conheça a regra <b>3-2-1</b> de backup.</p>",
    [stat("3-2-1", "Regra", "de backup", size=170)]),
   ("<p><b>3</b> cópias dos seus dados: a original e mais duas.</p>",
    [stat("3", "Cópias", "a original + 2 backups", black=False, color="blue", size=200)]),
   ("<p><b>2</b> tipos diferentes de armazenamento, como computador e HD externo, ou computador e nuvem.</p>",
    [stat("2", "Tipos", "de armazenamento", size=200)]),
   ("<p><b>1</b> cópia <b>fora</b> do local, para o caso de roubo, incêndio ou ataque.</p>",
    [stat("1", "Fora do local", "na nuvem ou em outro endereço", black=False, color="blue", size=200)]),
   ("<p>E o passo que quase todo mundo esquece: <b>testar</b> se o backup realmente restaura.</p>",
    [texto("Teste", 'Backup que nunca foi testado é <span class=coral>só esperança</span>.', black=True, fs=40)]),
   ])

P("gerenciador-de-senhas", "tech",
  "Usa a mesma senha em vários sites? Um vazamento pode abrir todas as portas.",
  "Um gerenciador de senhas cria e guarda senhas diferentes para cada site. Você só lembra de uma senha mestra.",
  "#senhas #seguranca #tecnologia #privacidade #dicas",
  "Senha forte que você não precisa decorar.",
  [("<p>Você usa a <b>mesma senha</b> em vários sites?</p><p>Então um vazamento pode abrir todas as portas.</p>",
    [aviso("Senha repetida", "um vazamento abre várias contas", "🔑", cor=CORAL),
     stat("1", "Senha mestra", "para guardar todas as outras", black=False, color="blue", size=190)]),
   ("<p>O gerenciador de senhas cria e guarda senhas <b>fortes e diferentes</b> para cada site.</p>",
    [lista("O gerenciador", ["Cria senhas fortes", "Guarda com criptografia", "Preenche sozinho"])]),
   ("<p>Você só precisa lembrar de <b>uma senha mestra</b>, forte e que não usa em mais nenhum lugar.</p>",
    [texto("Senha mestra", 'Longa, única e <span class=coral>só sua</span>.', black=True, fs=44)]),
   ("<p>Existem opções gratuitas e pagas, e navegadores como Chrome e Safari já têm um <b>gerenciador embutido</b>.</p>",
    [lista("Opções", ["Gerenciador do navegador", "Apps dedicados", "Planos para equipes"])]),
   ("<p>Combine com a <b>verificação em duas etapas</b> na conta do gerenciador.</p>",
    [fluxo("Proteção completa", ["Senhas únicas", "Senha mestra forte", "Duas etapas"])]),
   ])

P("como-reconhecer-phishing", "tech",
  "Aquele e-mail do banco pode ser golpe. 5 sinais de phishing.",
  "Urgência, remetente estranho, link suspeito, pedido de senha e anexo inesperado. Na dúvida, abra o app oficial.",
  "#phishing #golpe #seguranca #tecnologia #dicas",
  "Na dúvida, não clique.",
  [("<p>Aquele e-mail \"do banco\" pode ser <b>golpe</b>.</p><p>5 sinais de phishing para reconhecer na hora.</p>",
    [texto("Assunto do e-mail", '"<span class=coral>URGENTE:</span> sua conta será bloqueada hoje"', black=True, fs=32),
     stat("5", "Sinais", "de golpe", black=False, color="blue", size=200)]),
   ("<p><b>1. Urgência:</b> ameaça de bloqueio ou prazo curto.</p><p><b>2. Remetente estranho:</b> endereço que imita o original.</p>",
    [atencao("Sinais 1 e 2", ["Urgência e ameaça", "Remetente parecido, mas diferente"])]),
   ("<p><b>3. Link suspeito:</b> antes de clicar, segure o dedo ou passe o mouse por cima e veja o endereço real.</p>",
    [pilula("Link real", "banco-atualizacao-segura.xyz", "Não é o site do seu banco")]),
   ("<p><b>4. Pedido de dados:</b> senha, código ou token.</p><p><b>5. Anexo inesperado</b>, principalmente arquivo compactado.</p>",
    [atencao("Sinais 4 e 5", ["Pedem senha ou código", "Anexo inesperado"])]),
   ("<p>Na dúvida, <b>não clique</b>: abra o app ou o site oficial digitando o endereço você mesmo.</p>",
    [fluxo("Na dúvida", ["Não clique", "Abra o app oficial", "Confira lá"])]),
   ])

P("golpes-no-pix", "tech",
  "O Pix é rápido para você e para o golpista. Veja os golpes mais comuns.",
  "Falso parente, comprovante editado e QR Code adulterado. Confira o recebedor e o extrato, e avise o banco na hora se cair em golpe.",
  "#pix #golpe #seguranca #bancocentral #dicas",
  "Compartilhe com quem precisa ver isso.",
  [("<p>O Pix é rápido para você e <b>para o golpista</b>.</p><p>Os golpes mais comuns e como se proteger.</p>",
    [aviso("Pix", "confira antes de confirmar", "!", cor=CORAL),
     nao("Golpes comuns", ["Falso parente", "Falso comprovante", "QR Code adulterado"], fs=27)]),
   ("<p><b>Falso parente:</b> alguém com a foto de um familiar diz que trocou de número e pede um Pix urgente.</p>",
    [texto("Mensagem típica", '"Oi, troquei de número. Pode me fazer um <span class=coral>Pix urgente</span>?"', black=True, fs=34)]),
   ("<p><b>Falso comprovante:</b> o \"cliente\" manda um comprovante editado. Confira sempre o valor <b>no extrato</b>, não na imagem.</p>",
    [lista("Para quem vende", ["Confira no extrato", "Não libere pela imagem", "Desconfie da pressa"])]),
   ("<p><b>QR Code adulterado:</b> antes de confirmar, confira o <b>nome do recebedor</b> que aparece na tela.</p>",
    [pilula("Tela de confirmação", "Recebedor: confira o nome", "Antes de digitar a senha")]),
   ("<p>Caiu em golpe? Avise o banco <b>na hora</b>. O Banco Central tem o <b>Mecanismo Especial de Devolução (MED)</b> para esses casos.</p>",
    [fluxo("Se cair em golpe", ["Avise o banco", "Registre o boletim", "Acompanhe o MED"])]),
   ])

P("cuidado-com-wi-fi-publico", "tech",
  "Wi-Fi de graça no aeroporto ou no café? Cuidado com o que você faz nele.",
  "Evite banco, compras e senhas em redes abertas. Prefira os dados móveis e desative a conexão automática.",
  "#seguranca #wifi #tecnologia #privacidade #dicas",
  "Internet grátis pode sair caro.",
  [("<p>Wi-Fi de graça no aeroporto ou no café?</p><p>Cuidado com o que você faz nele.</p>",
    [aviso("Wi-Fi público", "rede aberta, cuidado redobrado", "📶", cor=CORAL),
     nao("Evite", ["Banco", "Compras", "Senhas"], fs=30)]),
   ("<p>Em redes abertas, outras pessoas estão na <b>mesma rede</b>, e golpistas podem criar redes falsas com nomes parecidos.</p>",
    [texto("Rede falsa", '"Cafe_WiFi_Gratis" pode <span class=coral>não ser do café</span>.', black=True, fs=36)]),
   ("<p>Evite acessar o <b>banco</b>, fazer compras e digitar senhas em Wi-Fi público.</p>",
    [nao("Evite", ["Aplicativo do banco", "Compras com cartão", "Login em contas importantes"])]),
   ("<p>Prefira os <b>dados móveis</b> do celular ou roteie a internet do seu aparelho.</p>",
    [lista("Prefira", ["Dados móveis", "Roteador do celular", "VPN confiável"])]),
   ("<p>Confira se os sites usam <b>HTTPS</b> e desative a conexão automática em redes abertas.</p>",
    [lista("Configure", ["Sites com HTTPS", "Sem conexão automática", "Esquecer redes públicas"])]),
   ])

P("atualizacoes-de-seguranca", "tech",
  "Aquela atualização que você vive adiando pode fechar uma brecha de segurança.",
  "Atualizações corrigem falhas conhecidas. Ative o modo automático e inclua roteador, impressoras e o site da empresa.",
  "#seguranca #atualizacao #tecnologia #ciberseguranca #dicas",
  "Atualizar é o jeito mais barato de se proteger.",
  [("<p>Aquela <b>atualização</b> que você vive adiando pode ser a que fecha uma brecha de segurança.</p>",
    [aviso("Atualização disponível", "Lembrar mais tarde?", "⟳", black=False, cor=AZUL),
     texto("Na prática", 'Adiar pode deixar a <span class=coral>porta aberta</span>.', black=True, fs=34)]),
   ("<p>Atualizações corrigem <b>falhas de segurança</b> já conhecidas, algumas delas já exploradas por criminosos.</p>",
    [lista("O que a atualização traz", ["Correções de segurança", "Correções de erros", "Recursos novos"])]),
   ("<p>Exemplo real: em setembro, a Cisco lançou uma correção de emergência para uma falha de gravidade <b>10, a máxima</b>, que já estava sendo explorada.</p>",
    [stat("10/10", "Gravidade", "falha corrigida às pressas pela Cisco", size=140)]),
   ("<p>Ative a <b>atualização automática</b> no celular, no computador, no navegador e nos apps.</p>",
    [lista("Atualização automática", ["Celular", "Computador", "Navegador", "Aplicativos"])]),
   ("<p>Na empresa, inclua também roteador, impressoras e o <b>site</b>: plugins desatualizados são porta de entrada.</p>",
    [atencao("Não esqueça", ["Roteador", "Impressoras", "Site e plugins"])]),
   ], fonte="SecurityWeek (setembro/2026), para o exemplo da Cisco")

P("golpe-de-voz-clonada-com-ia", "tech",
  "Golpistas já usam IA para imitar vozes. Veja como se proteger.",
  "Desconfie de urgência e de pedido de Pix, combine uma palavra-código com a família e, na dúvida, ligue de volta.",
  "#golpe #deepfake #seguranca #inteligenciaartificial #pix",
  "Compartilhe com quem você quer proteger.",
  [("<p>Golpistas já usam IA para <b>imitar vozes</b>.</p><p>Veja como proteger você e a sua família.</p>",
    [aviso("\"Mãe, sou eu...\"", "a voz pode ser falsa", "📞", cor=CORAL),
     lista("Proteja-se", ["Palavra-código", "Ligue de volta", "Desconfie da pressa"], fs=27)]),
   ("<p>Como funciona: com poucos segundos de áudio, ferramentas de IA conseguem <b>imitar uma voz</b>.</p>",
    [texto("Clonagem de voz", 'Alguns segundos de áudio podem bastar para <span class=coral>imitar uma voz</span>.', black=True, fs=36)]),
   ("<p>O roteiro costuma se repetir: <b>urgência</b>, pedido de dinheiro e pedido de segredo.</p>",
    [atencao("Sinais de golpe", ["Urgência", "Pedido de Pix", "\"Não conta pra ninguém\""])]),
   ("<p>Combine uma <b>palavra-código</b> com a família. Quem não souber, não é quem diz ser.</p>",
    [pilula("Palavra-código", "••••••", "Combinada só entre vocês")]),
   ("<p>Na dúvida, <b>desligue e ligue de volta</b> para o número que você já conhece.</p>",
    [fluxo("Na dúvida", ["Desligue", "Ligue para o número conhecido", "Confirme"])]),
   ])
